### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by MadMakz** [Jules-WinnfieldX/CyberDropDownloader#105]
Debian 11.3.

`pip install cyberdrop-dl`

`Collecting cyberdrop-dl
  Using cached cyberdrop_dl-2.14.3-py3-none-any.whl (33 kB)
Requirement already satisfied: aiohttp>=3.8.1 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (3.8.1)
Requirement already satisfied: tldextract>=3.2.0 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (3.2.0)
Requirement already satisfied: gofile-client>=1.0.1 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: aiofiles>=0.8.0 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: yarl>=1.7.2 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (1.7.2)
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (2.27.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (2021.10.8)
Requirement already satisfied: colorama>=0.4.4 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (0.4.4)
Requirement already satisfied: beautifulsoup4>=4.11.0 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.8/site-packages (from cyberdrop-dl) (4.64.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (1.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (2.0.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/site-packages (from aiohttp>=3.8.1->cyberdrop-dl) (1.2.0)
Requirement already satisfied: soupsieve>1.2 in ./.local/lib/python3.8/site-packages (from beautifulsoup4>=4.11.0->cyberdrop-dl) (1.9.5)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.8/site-packages (from requests>=2.27.1->cyberdrop-dl) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests>=2.27.1->cyberdrop-dl) (1.25.10)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.8/site-packages (from tldextract>=3.2.0->cyberdrop-dl) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.8/site-packages (from tldextract>=3.2.0->cyberdrop-dl) (3.6.0)
Requirement already satisfied: six in ./.local/lib/python3.8/site-packages (from requests-file>=1.4->tldextract>=3.2.0->cyberdrop-dl) (1.13.0)
Installing collected packages: cyberdrop-dl
Successfully installed cyberdrop-dl-2.14.3`

`cyberdrop-dl`

`Traceback (most recent call last):
  File "/usr/local/bin/cyberdrop-dl", line 5, in <module>
    from cyberdrop_dl.main import main
  File "/usr/local/lib/python3.8/site-packages/cyberdrop_dl/main.py", line 4, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'`

**Comment by Jules-WinnfieldX** [comment]
I was under the impression SQLite was a standard python library, turns out it's an optional python library no included on a lot of linux distros. I'll have to change to something like SQLAlchemy

**Comment by Jules-WinnfieldX** [comment]
https://linuxhint.com/install-sqlite-on-debian-11/

In terms of file based database systems this is basically it. You can follow the link above on how to include it in your python.

**Comment by Jules-WinnfieldX** [comment]
https://stackoverflow.com/a/24449632
