### ISSUE TITLE
[BUG] Error trying to download SimpCity threads

### ISSUE THREAD

**Issue by axel845845** [Jules-WinnfieldX/CyberDropDownloader#192]
It says something about logging in with my account, but I don't know how to do it, and I don't think I need to log in with my account either.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9420375/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You edit the start start file and change
`cyberdrop-dl` to `cyberdrop-dl --simpcity-username "axel845845" --simpcity-password "Password"`

**Comment by axel845845** [comment]
What if I don't have a password on my account?

**Comment by Jules-WinnfieldX** [comment]
> What if I don't have a password on my account?

what do you mean? you have to have a password. That's how an account works.

**Comment by axel845845** [comment]
When creating an account in Simpcity it does not necessarily ask you for a password, as I did it directly by logging in with Google

**Comment by Jules-WinnfieldX** [comment]
> When creating an account in Simpcity it does not necessarily ask you for a password, as I did it directly by logging in with Google

forgot they added that, this doesn't support google login as of now. You'd have to make an account the traditional way.

**Comment by axel845845** [comment]
Ok, I will do it. The file I need to edit is this one: Start Windows.bat?

**Comment by Jules-WinnfieldX** [comment]
if you are on windows, yep.

**Comment by axel845845** [comment]
I keep getting an error

**Comment by Jules-WinnfieldX** [comment]
What error would that be

**Comment by axel845845** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9420605/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You either didn't save the start file, or you are using a different one to run the program.

**Comment by axel845845** [comment]
Do I have to edit it with python (Star Windows.bat) or just change the name?

**Comment by Jules-WinnfieldX** [comment]
No, not python. Just open it in a text editor. notepad, notepad++, etc.

**Comment by axel845845** [comment]
I get this 

pip install --upgrade cyberdrop-dl
cyberdrop-dl
pausa

**Comment by Jules-WinnfieldX** [comment]
As I said above, 

You edit the start start file and change the line that says just
`cyberdrop-dl` to `cyberdrop-dl --simpcity-username "axel845845" --simpcity-password "Password"`

**Comment by axel845845** [comment]
pip install --upgrade cyberdrop-dl
cyberdrop-dl cyberdrop-dl --simpcity-username "JIGSAW9" --simpcity-password "hdgdggdgdg"
pause

Something like that?

**Comment by Jules-WinnfieldX** [comment]
yep, like that.

**Comment by axel845845** [comment]
We are running version 3.2.8 of Cyberdrop Downloader
Starting Scrape
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/
Traceback (most recent call last):
  File "c:\robodk\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\robodk\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\RoboDK\Python37\Scripts\cyberdrop-dl.exe\__main__.py", line 9, in <module>
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 124, in main
    loop.run_until_complete(download_all(args))
  File "c:\robodk\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 85, in download_all
    simpcity_auth, args.separate_posts, skip_data)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 19, in scrape
    await asyncio.gather(*tasks)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 260, in map_url
    if key in url_to_map.host:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Jules-WinnfieldX** [comment]
I honestly don't know how that's possible. Give me a few

**Comment by axel845845** [comment]
Ok, I guess if it doesn't work I'll have to do it the manual way haha.

**Comment by Jules-WinnfieldX** [comment]
make sure have urls in urls.txt, try running again. Might have to do it twice till it says version 3.2.9 when it's running.

**Comment by Jules-WinnfieldX** [comment]
whoops nvm

**Comment by axel845845** [comment]
We are running version 3.2.9 of Cyberdrop Downloader
Starting Scrape
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/page-2
Traceback (most recent call last):
  File "c:\robodk\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\robodk\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\RoboDK\Python37\Scripts\cyberdrop-dl.exe\__main__.py", line 9, in <module>
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 128, in main
    loop.run_until_complete(download_all(args))
  File "c:\robodk\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 90, in download_all
    simpcity_auth, args.separate_posts, skip_data)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 19, in scrape
    await asyncio.gather(*tasks)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 260, in map_url
    if key in url_to_map.host:
TypeError: argument of type 'NoneType' is not iterable

D:\Cyberdrop_DL.V3>pause
Presione una tecla para continuar . . .


NOT WORK

**Comment by Jules-WinnfieldX** [comment]
Yea, I knew that was going to happen. 3.3.1 should if I understand what the issue is.

**Comment by axel845845** [comment]
If you now say that I am running version 3.3.1

We are running version 3.3.1 of Cyberdrop Downloader
Starting Scrape
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/page-2
Traceback (most recent call last):
  File "c:\robodk\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\robodk\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\RoboDK\Python37\Scripts\cyberdrop-dl.exe\__main__.py", line 9, in <module>
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 129, in main
    loop.run_until_complete(download_all(args))
  File "c:\robodk\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 91, in download_all
    simpcity_auth, args.separate_posts, skip_data)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 19, in scrape
    await asyncio.gather(*tasks)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 260, in map_url
    if key in url_to_map.host:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Jules-WinnfieldX** [comment]
3.3.2?

**Comment by axel845845** [comment]
We are running version 3.3.2 of Cyberdrop Downloader
Starting Scrape
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/
Starting scrape of https://simpcity.st/threads/julia-kul-juliakul_official.14444/page-2
Traceback (most recent call last):
  File "c:\robodk\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\robodk\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\RoboDK\Python37\Scripts\cyberdrop-dl.exe\__main__.py", line 9, in <module>
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 129, in main
    loop.run_until_complete(download_all(args))
  File "c:\robodk\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\main.py", line 91, in download_all
    simpcity_auth, args.separate_posts, skip_data)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 19, in scrape
    await asyncio.gather(*tasks)
  File "c:\robodk\python37\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 262, in map_url
    if key in url_to_map.host:
TypeError: argument of type 'NoneType' is not iterable

MMMM :/

**Comment by Jules-WinnfieldX** [comment]
3.3.3? fingers crossed

**Comment by axel845845** [comment]
Unbelievable, I don't know what you did, but it has worked now.
Thank you for your hard work and effort.

**Comment by Jules-WinnfieldX** [comment]
Fixed a bug I've never seen before nor know why it exists. but if it works it works!
