### ISSUE TITLE
[BUG] Cyberdrop rename issue

### ISSUE THREAD

**Issue by bratworst** [Jules-WinnfieldX/CyberDropDownloader#199]
Snippet of Debug log included below, the script is renaming files to img-01 instead of fs-01

**Folder name and file link manually edited for privacy/clarity.**

2022-08-28 16:09:59,184:DEBUG:downloaders:downloaders.py:211:522, message='', url=URL('https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg')
2022-08-28 16:09:59,185:DEBUG:downloaders:downloaders.py:214:Error status code: 522
2022-08-28 16:09:59,185:DEBUG:downloaders:downloaders.py:36:Retrying (8) https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg...
2022-08-28 16:10:01,456:DEBUG:downloaders:downloaders.py:211:522, message='', url=URL('https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg')
2022-08-28 16:10:01,456:DEBUG:downloaders:downloaders.py:214:Error status code: 522
2022-08-28 16:10:01,456:DEBUG:downloaders:downloaders.py:34:Skipping https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg...
2022-08-28 16:10:01,456:DEBUG:downloaders:downloaders.py:256:Traceback (most recent call last):
  File "..\Python\Python310\lib\site-packages\cyberdrop_dl\client\downloaders.py", line 196, in download_file
    await session.download_file(url, referer, current_throttle, range, original_filename, filename,
  File "..\Python\Python310\lib\site-packages\cyberdrop_dl\client\client.py", line 125, in download_file
    async with self.client_session.get(url, headers=headers, ssl=self.client.ssl_context,
  File "..\Python\Python310\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "..\Python\Python310\lib\site-packages\aiohttp\client.py", line 640, in _request
    resp.raise_for_status()
  File "..\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 522, message='', url=URL('https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\Python\Python310\lib\site-packages\cyberdrop_dl\client\downloaders.py", line 253, in download_and_store
    await self.download_file(url, referral=referral, filename=filename, session=session,
  File "..\Python\Python310\lib\site-packages\cyberdrop_dl\client\downloaders.py", line 30, in wrapper
    return await f(self, *args, **kwargs)
  File "..\Python\Python310\lib\site-packages\cyberdrop_dl\client\downloaders.py", line 224, in download_file
    raise FailureException(e)
cyberdrop_dl.client.downloaders.FailureException: 522, message='', url=URL('https://img-01.cyberdrop.to/DSC12345-abcdefgh.jpg')

2022-08-28 16:10:01,456:DEBUG:base_functions:base_functions.py:41:
Error attempting DSC12345-abcdefgh.jpg: See downloader.log for details

**Comment by Jules-WinnfieldX** [comment]
img-01 is a valid cyberdrop domain. To understand more though I'd need to know what you mean by renaming, what did it start as?

The issue is cyberdrop however for album scraping. Half of cyberdrops servers simply do not work. Which ones not working depends on the day.

**Comment by scorv** [comment]
A fix for the cyberdrop issue is to change the URL of the cyberdrop image
while scraping the gallery for a list of images you can make two changes to the URL to get it working

using the following as an example
https://fs-05.cyberdrop.to/fakefilename.jpg
remove the subdomain so instead of https://fs-05.cyb.... it becomes https://cyb....
change from to to me,  cyberdrop.to/ to cyberdrop.me/
leaving a URL of https://cyberdrop.me/fakefilename.jpg that will work

Ideally you could set it up to manipulate the string during the first retry but guessing it might be easier just to do it in the crawlers file.

Hope this comment has been even a tiny fraction of how useful your downloader has been  :)

**Comment by Jules-WinnfieldX** [comment]
Added Scorv's method, will be out in a few.
