### ISSUE TITLE
[BUG] [3.4.14] Bunkr.is cdn regression

### ISSUE THREAD

**Issue by ms6676749** [Jules-WinnfieldX/CyberDropDownloader#240]
URLs.txt has a link of a forum post having a cdn[0-9].bunkr.is link. Forum scraper finds the cdn bunkr link but the download fails. This cdn link is redirected to stream.bunkr.is/v/ when visiting the site through a web browser. Same issue when cdn link is used in URLs.txt instead of the forum post. Changing the cdn addresses to stream.bunkr.is/foo fixed the issue. A recent update to Cyberdownloader did just that. However, the bug is back with 3.4.14.

A previous version fixed this, but the issue is back. From the log, it seems that cyberdropdownloader is handling the cdn link only (no change from ```cdn[0-9].bunkr.is``` to ```stream.bunkr.is/v/```.

```
2022-10-15 07:10:41,854:DEBUG:selector_events:selector_events.py:59:Using selector: EpollSelector
2022-10-15 07:10:41,927:DEBUG:base_functions:base_functions.py:48:We are running version 3.4.14 of Cyberdrop Downloader
2022-10-15 07:10:41,939:DEBUG:main:main.py:90:Starting Cyberdrop-DL
2022-10-15 07:10:41,939:DEBUG:main:main.py:91:Using authorization arguments: {'simpcity_username': '!REDACTED!', 'simpcity_password': '!REDACTED!', 'socialmediagirls_username': None, 'socialmediagirls_password': '!REDACTED!', 'xbunker_username': None, 'xbunker_password': '!REDACTED!'}
2022-10-15 07:10:41,939:DEBUG:main:main.py:92:Using file arguments: {'input_file': PosixPath('URLs.txt'), 'output_folder': PosixPath('Downloads'), 'db_file': PosixPath('download_history.sqlite')}
2022-10-15 07:10:41,939:DEBUG:main:main.py:93:Using jdownloader arguments: {'jdownloader_enable': False, 'jdownloader_username': None, 'jdownloader_password': '!REDACTED!', 'jdownloader_device': None}
2022-10-15 07:10:41,939:DEBUG:main:main.py:94:Using runtime arguments: {'threads': 0, 'attempts': 10, 'disable_attempt_limit': False, 'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5, 'include_id': False, 'exclude_videos': False, 'exclude_images': False, 'exclude_audio': False, 'exclude_other': False, 'ignore_history': False, 'output_last_forum_post': False, 'separate_posts': False, 'proxy': None, 'skip_hosts': []}
2022-10-15 07:10:41,950:DEBUG:base_functions:base_functions.py:48:Starting Scrape
2022-10-15 07:10:41,950:DEBUG:base_functions:base_functions.py:48:Starting scrape of https://simpcity.su/threads/clara-chan-clara_chan.21815/post-1085201
2022-10-15 07:10:49,067:DEBUG:base_functions:base_functions.py:48:Starting scrape of https://cdn10.bunkr.is/5825056.mp4-nIUj5i11.mp4
2022-10-15 07:10:50,183:DEBUG:Bunkr_Spider:Bunkr_Spider.py:55:Error encountered while handling https://cdn10.bunkr.is/5825056.mp4-nIUj5i11.mp4
Traceback (most recent call last):
  File "/home/synapse/.local/lib/python3.8/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 37, in fetch
    files = build_id['props']['pageProps']['album']['files']
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/.local/lib/python3.8/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 41, in fetch
    text = await session.get_text(json_fetch)
  File "/home/synapse/.local/lib/python3.8/site-packages/cyberdrop_dl/client/client.py", line 51, in get_text
    async with self.client_session.get(url, ssl=self.client.ssl_context) as response:
  File "/home/synapse/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/synapse/.local/lib/python3.8/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/synapse/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://cdn10.bunkr.is/_next/data/H4vxvBBHw5QJXZNx-h31g/5825056.mp4-nIUj5i11.mp4.json')
2022-10-15 07:10:50,185:DEBUG:base_functions:base_functions.py:48:Error scraping https://cdn10.bunkr.is/5825056.mp4-nIUj5i11.mp4
2022-10-15 07:10:50,185:DEBUG:Bunkr_Spider:Bunkr_Spider.py:57:404, message='Not Found', url=URL('https://cdn10.bunkr.is/_next/data/H4vxvBBHw5QJXZNx-h31g/5825056.mp4-nIUj5i11.mp4.json')
2022-10-15 07:10:50,185:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://cdn10.bunkr.is/5825056.mp4-nIUj5i11.mp4
2022-10-15 07:10:50,194:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://simpcity.su/threads/clara-chan-clara_chan.21815/post-1085201
2022-10-15 07:10:50,194:ERROR:main:main.py:141:ValueError No links
2022-10-15 07:10:50,194:DEBUG:base_functions:base_functions.py:48:No links found duing scraping, check passwords or that the urls are accessible
2022-10-15 07:10:50,195:DEBUG:base_functions:base_functions.py:48:This program does not currently support password protected albums.
2022-10-15 07:10:50,195:DEBUG:sql_helper:sql_helper.py:112:Successfully closed sqlite database connection
```

**Comment by Jules-WinnfieldX** [comment]
Problem here is it doesn't lay in that [0-9]. Should be fixed in 3.4.16
