### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by satyanvesi** [Jules-WinnfieldX/CyberDropDownloader#242]
i am running it in termux on android it gives like this..

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/cyberdrop-dl", line 5, in <module>
    from cyberdrop_dl.main import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 18, in <module>
    from cyberdrop_dl.client.downloaders import get_downloaders
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cyberdrop_dl/client/downloaders.py", line 10, in <module>
    import aiofiles.os
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/aiofiles/os.py", line 31, in <module>
    link = wrap(os.link)
AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?

please suggest a fix or any idea

**Comment by Jules-WinnfieldX** [comment]
I don't officially support android, I don't have any devices I could test this on. You'd be better off seeking help from a termux community, or android enthusiast community.

**Comment by KazKaz90** [comment]
Is there any new information or progress on this?

**Comment by Jules-WinnfieldX** [comment]
> Is there any new information or progress on this?

this remains the same from my end. It seems like a limitation of the OS module on android, which is a default python module. Nothing I can do about it.

**Comment by neuri48** [comment]
pip install aiofiles 0.8.0
