### ISSUE TITLE
[BUG] Exception: Couldn't get link from HTML

### ISSUE THREAD

**Issue by mschairspam** [Jules-WinnfieldX/CyberDropDownloader#244]
**Describe the bug**
Some bunkr links don't download, even though they're openable in browser. The links I've identified here follow this format:
`stream.bunkr.is/v/...`

Output after running the script:

> Error scraping https://stream.bunkr.is/v/...
> Finished scraping https://stream.bunkr.is/v/...

**To Help Reproduce**
Use this URLs.txt... these are NSFW albums. Couldn't find a SFW album with which to reproduce this error. Sooo either accept my apologies, or you're welcome
<details>
  <summary>URLs.txt</summary>

https://stream.bunkr.is/v/Yourboyfcisco---Edge-Me-Nikki-Sorayama-WV0eC0Lc.mp4
https://stream.bunkr.is/v/Sophia-Nikki-ye1tq1X2.mp4
https://stream.bunkr.is/v/Nikki-Sophia-Lena-Troy-zGipAWvW.mp4
https://stream.bunkr.is/v/R57l.mp4
https://stream.bunkr.is/v/2022-06-14_0h37osowugg4cey33ughn_source-ZKbzO9jB.mp4
https://stream.bunkr.is/v/FFqg.mp4
</details>

**Setup Information**
 - OS: macOS Monterey 12.3.1
 - Cyberdrop Downloader Version 3.4.18

**Downloader.log file**
Again, apologies as this references NSFW albums.
just look at this snippet, it should give enough info without looking at the actual log

> 2022-10-17 16:00:44,579:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/...
> Traceback (most recent call last):
>   File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
>     raise Exception("Couldn't get link from HTML")
> Exception: Couldn't get link from HTML
> 2022-10-17 16:00:44,579:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/FFqg.mp4
> 2022-10-17 16:00:44,579:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
> 2022-10-17 16:00:44,579:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/...

<details>
  <summary>URLs.txt</summary>

2022-10-17 16:00:44,488:DEBUG:selector_events:selector_events.py:59:Using selector: KqueueSelector
2022-10-17 16:00:44,496:DEBUG:base_functions:base_functions.py:48:We are running version 3.4.18 of Cyberdrop Downloader
2022-10-17 16:00:44,504:DEBUG:main:main.py:90:Starting Cyberdrop-DL
2022-10-17 16:00:44,504:DEBUG:main:main.py:91:Using authorization arguments: {'simpcity_username': None, 'simpcity_password': '!REDACTED!', 'socialmediagirls_username': None, 'socialmediagirls_password': '!REDACTED!', 'xbunker_username': None, 'xbunker_password': '!REDACTED!'}
2022-10-17 16:00:44,505:DEBUG:main:main.py:92:Using file arguments: {'input_file': PosixPath('URLs.txt'), 'output_folder': PosixPath('Downloads'), 'db_file': PosixPath('download_history.sqlite')}
2022-10-17 16:00:44,505:DEBUG:main:main.py:93:Using jdownloader arguments: {'jdownloader_enable': False, 'jdownloader_username': None, 'jdownloader_password': '!REDACTED!', 'jdownloader_device': None}
2022-10-17 16:00:44,505:DEBUG:main:main.py:94:Using runtime arguments: {'threads': 0, 'attempts': 10, 'disable_attempt_limit': False, 'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5, 'include_id': False, 'exclude_videos': False, 'exclude_images': False, 'exclude_audio': False, 'exclude_other': False, 'ignore_history': False, 'output_last_forum_post': False, 'separate_posts': False, 'proxy': None, 'skip_hosts': []}
2022-10-17 16:00:44,515:DEBUG:base_functions:base_functions.py:48:Starting Scrape
2022-10-17 16:00:44,579:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/FFqg.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,579:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/FFqg.mp4
2022-10-17 16:00:44,579:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,579:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/FFqg.mp4
2022-10-17 16:00:44,582:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/Nikki-Sophia-Lena-Troy-zGipAWvW.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,582:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/Nikki-Sophia-Lena-Troy-zGipAWvW.mp4
2022-10-17 16:00:44,582:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,582:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/Nikki-Sophia-Lena-Troy-zGipAWvW.mp4
2022-10-17 16:00:44,590:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/R57l.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,590:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/R57l.mp4
2022-10-17 16:00:44,590:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,590:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/R57l.mp4
2022-10-17 16:00:44,593:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/Sophia-Nikki-ye1tq1X2.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,593:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/Sophia-Nikki-ye1tq1X2.mp4
2022-10-17 16:00:44,593:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,593:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/Sophia-Nikki-ye1tq1X2.mp4
2022-10-17 16:00:44,595:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/Yourboyfcisco---Edge-Me-Nikki-Sorayama-WV0eC0Lc.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,595:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/Yourboyfcisco---Edge-Me-Nikki-Sorayama-WV0eC0Lc.mp4
2022-10-17 16:00:44,595:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,595:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/Yourboyfcisco---Edge-Me-Nikki-Sorayama-WV0eC0Lc.mp4
2022-10-17 16:00:44,598:DEBUG:Bunkr_Spider:Bunkr_Spider.py:75:Error encountered while handling https://stream.bunkr.is/v/2022-06-14_0h37osowugg4cey33ughn_source-ZKbzO9jB.mp4
Traceback (most recent call last):
  File "/Users/mschairspam/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Bunkr_Spider.py", line 70, in stream
    raise Exception("Couldn't get link from HTML")
Exception: Couldn't get link from HTML
2022-10-17 16:00:44,598:DEBUG:base_functions:base_functions.py:48:Error scraping https://stream.bunkr.is/v/2022-06-14_0h37osowugg4cey33ughn_source-ZKbzO9jB.mp4
2022-10-17 16:00:44,598:DEBUG:Bunkr_Spider:Bunkr_Spider.py:77:Couldn't get link from HTML
2022-10-17 16:00:44,598:DEBUG:base_functions:base_functions.py:48:Finished scrape of https://stream.bunkr.is/v/2022-06-14_0h37osowugg4cey33ughn_source-ZKbzO9jB.mp4
2022-10-17 16:00:44,599:ERROR:main:main.py:141:ValueError No links
2022-10-17 16:00:44,599:DEBUG:base_functions:base_functions.py:48:No links found duing scraping, check passwords or that the urls are accessible
2022-10-17 16:00:44,599:DEBUG:base_functions:base_functions.py:48:This program does not currently support password protected albums.
2022-10-17 16:00:44,600:DEBUG:sql_helper:sql_helper.py:112:Successfully closed sqlite database connection

</details>

because i isolated the problem links, running the script does not find any links, and rest assured none of these albums are password protected.

**Comment by mschairspam** [comment]
there might actually be something wrong with bunkr at the time of this posting... one of the links i provided ([NSFW 1](https://stream.bunkr.is/v/FFqg.mp4)) no longer opens, and instead renders this:
![Screen Shot 2022-10-17 at 16 43 10](https://user-images.githubusercontent.com/116041316/196303581-213467c3-84bd-4fcc-8248-ddcc3c014a23.png)

was this file deleted? possibly! but i think not.

my test:
1. i used this script to download a video from **my own album** ([NSFW 2](https://stream.bunkr.is/v/guochan2048.com--%E3%80%90%E9%87%8D%E7%A3%85%E5%B7%A8%E4%B9%B3%E3%80%91%E6%9E%81%E5%93%81%E7%BD%91%E7%BA%A2%E3%80%8E%E6%88%B4%E6%B8%83%E6%AC%A3%E3%80%8F%E6%9C%80%E6%96%B0%E4%B8%8E%E5%9C%9F%E8%B1%AA%E5%95%AA%E5%95%AA%E9%9C%B2%E7%82%B9%E9%81%93%E5%85%B7%E6%8F%92%E9%80%BC-%E6%B8%85%E6%99%B0%E5%AF%B9%E7%99%BD-%E5%9C%9F%E8%B1%AA%E6%8F%89%E6%90%93%E5%B7%A8%E4%B9%B3-%E5%A8%87%E5%96%98%E5%91%BB%E5%90%9F-%E6%8A%BD%E6%8F%92%E7%89%B9%E5%86%99-%E9%AB%98%E6%B8%85720P%E7%89%88-JYZTp5y8.mp4)) and it returned the same "Couldn't get link from HTML" error.
2. i tried to open this link in the browser and it returned the same error in the screenshot
3. i went into my bunkr dashboard, opened the album, and the video (labeled NSFW 2) was still there. I clicked it and it opened flawlessly
4. I copied the link into URLs.txt and
5. THE SCRIPT DOWNLOADED IT PROPERLY THIS TIME

Maybe bunkr is doing some weird caching or pre-rendering that's messing up some videos..?

**Comment by Jules-WinnfieldX** [comment]
That error occurs because the bunkr stream link doesn't always load all the information correctly. I have a theory that it's location dependant. Try VPNing in to the deep south if you are in the pacific northwest.

**Comment by mschairspam** [comment]
that's a good theory. i apologize if that was on your FAQ and i missed it.

**Comment by Jules-WinnfieldX** [comment]
*it's not, but should be*
