### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by SharingSpoon** [Jules-WinnfieldX/CyberDropDownloader#246]
Sample error log below 

2022-10-23 11:25:13,823:DEBUG:client:client.py:131:Server for https://media-files4.bunkr.is/Katy-Perry-tZGgluvU.mp4 is either down or the file no longer exists
2022-10-23 11:25:13,824:DEBUG:downloaders:downloaders.py:259:Traceback (most recent call last):
  File "C:\Users\M\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cyberdrop_dl\client\downloaders.py", line 256, in download_and_store
    await self.download_file(url, referral=referral, filename=filename, session=session,
  File "C:\Users\M\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cyberdrop_dl\client\downloaders.py", line 30, in wrapper
    return await f(self, *args, **kwargs)
  File "C:\Users\M\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cyberdrop_dl\client\downloaders.py", line 203, in download_file
    await self.rename_file(filename, url, db_path)
  File "C:\Users\M\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cyberdrop_dl\client\downloaders.py", line 237, in rename_file
    temp_file.rename(complete_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Downloads\\Katy Perry\\Katy-Perry-tZGgluvU.mp4.part' -> 'Downloads\\Katy Perry\\Katy-Perry-tZGgluvU.mp4'

2022-10-23 11:25:13,825:DEBUG:base_functions:base_functions.py:43:
Error attempting Katy-Perry-tZGgluvU.mp4: See downloader.log for details

**Comment by Jules-WinnfieldX** [comment]
Usually this happens when the disk is full

**Comment by Jules-WinnfieldX** [comment]
What version of cyberdrop-dl are you running?

**Comment by SharingSpoon** [comment]
3.3.34

**Comment by Jules-WinnfieldX** [comment]
Try updating to the latest 3.5.1, and see if it makes a difference. Also make sure your disk isn't full.

But no, that link doesn't seem to be working on the website.

**Comment by SharingSpoon** [comment]
Thanks, n00b quesiton. Can i update from the command line? If I try and install via pip again it says everything is already satisfied,

**Comment by Jules-WinnfieldX** [comment]
You can update it from the command line using:
`pip install --upgrade cyberdrop-dl`

**Comment by SharingSpoon** [comment]
Thanks, givingit a go now

**Comment by Jules-WinnfieldX** [comment]
I'm going to assume this is fixed until notified otherwise.
