### ISSUE TITLE
AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?

### ISSUE THREAD

**Issue by mbledos69** [Jules-WinnfieldX/CyberDropDownloader#284]
$ cyberdrop-dl
Traceback (most recent call last):
File "/data/data/com.termux/files/usr/bin/cyberdrop-dl", line 5, in
from cyberdrop_dl.main import main
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 19, in
from cyberdrop_dl.client.downloaders import get_downloaders
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/cyberdrop_dl/client/downloaders.py", line 10, in
import aiofiles.os
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiofiles/os.py", line 31, in
link = wrap(os.link)
^^^^^^^
AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?

how to fix this issue?
i was already install the requirements on python also didnt work

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/242

See here
