### ISSUE TITLE
[BUG] sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by alexbababu** [Jules-WinnfieldX/CyberDropDownloader#305]
Looked for Issues with similiar describtion, but didnt find any :/

**Describe the bug**
When I start cyberdrop-dl with a url to an album in URLs.txt i get following.

> We are running version 3.6.48 of Cyberdrop Downloader
> Getting Run Args
> Traceback (most recent call last):
>   File "/home/alexander/anaconda3/bin/cyberdrop-dl", line 8, in <module>
>     sys.exit(main())
>   File "/home/alexander/anaconda3/lib/python3.9/site-packages/cyberdrop_dl/main.py", line 212, in main
>     loop.run_until_complete(director(args))
>   File "/home/alexander/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/home/alexander/anaconda3/lib/python3.9/site-packages/cyberdrop_dl/main.py", line 161, in director
>     await SQL_helper.sql_initialize()
>   File "/home/alexander/anaconda3/lib/python3.9/site-packages/cyberdrop_dl/base_functions/sql_helper.py", line 20, in sql_initialize
>     await self.create_tables()
>   File "/home/alexander/anaconda3/lib/python3.9/site-packages/cyberdrop_dl/base_functions/sql_helper.py", line 37, in create_tables
>     self.curs.execute(create_table_query)
> sqlite3.OperationalError: database is locked

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Freshly Install cyberdrop-dl in a conda environment
2. pip install cyberdrop-dl
3. first start cyberdrop-dl to create URLs.txt
4. fill URLs.txt with link
5. start cyberdrop-dl
6. get messages, but no download occurs

**Setup Information**
 - OS: Linux Ubuntu 22.04.1
 - Cyberdrop Downloader Version: 3.6.48
 -  Python 3.9.7 (same error with Python 3.10.)

**Downloader.log file**
2023-01-23 11:40:08,065:DEBUG:selector_events:selector_events.py:59:Using selector: EpollSelector
2023-01-23 11:40:08,067:DEBUG:base_functions:base_functions.py:61:We are running version 3.6.48 of Cyberdrop Downloader
2023-01-23 11:40:08,067:DEBUG:main:main.py:73:Creating Config
2023-01-23 11:40:08,068:DEBUG:base_functions:base_functions.py:142:Validating Config
2023-01-23 11:40:08,074:DEBUG:base_functions:base_functions.py:61:Getting Run Args
2023-01-23 11:40:08,081:DEBUG:base_functions:base_functions.py:205:Gathering Args
2023-01-23 11:40:08,081:DEBUG:main:main.py:97:Starting Cyberdrop-DL
2023-01-23 11:40:08,081:DEBUG:main:main.py:98:Using authorization arguments: {'pixeldrain_api_key': '!REDACTED!', 'simpcity_username': None, 'simpcity_password': '!REDACTED!', 'socialmediagirls_username': None, 'socialmediagirls_passwor>
2023-01-23 11:40:08,081:DEBUG:main:main.py:99:Using file arguments: {'input_file': PosixPath('URLs.txt'), 'output_folder': PosixPath('Downloads'), 'output_last_forum_post_file': PosixPath('URLs_last_post.txt'), 'db_file': PosixPath('dow>
2023-01-23 11:40:08,081:DEBUG:main:main.py:100:Using jdownloader arguments: {'jdownloader_enable': False, 'jdownloader_username': None, 'jdownloader_password': '!REDACTED!', 'jdownloader_device': None}
2023-01-23 11:40:08,081:DEBUG:main:main.py:101:Using runtime arguments: {'threads': 0, 'attempts': 10, 'required_free_space': 5, 'disable_attempt_limit': False, 'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5, 'include_id': F>
2023-01-23 11:40:13,103:DEBUG:sql_helper:sql_helper.py:133:Successfully closed sqlite database connection

**Comment by Jules-WinnfieldX** [comment]
Database locked errors (re-occurring) usually occur when a previous instance of the program didn't shut down successfully, This can be remedied by restarting the computer and in worst case scenarios deleting the DB file. Also make sure that the DB file has proper permissions to be able to be written to by the system and your user.

**Comment by C-BoT-AU** [comment]
Cyberdrop-DL v 4.1.14
Linux Mint 21.1 Vera (base: Ubuntu 22.04 jammy)

Running a new Linux Host/VM to de-clutter my main system and ran into this issue too. Usually on Windows I point Powershell or Command Prompt at my Cyberdrop directory stored on a NAS where I have config files/subfolders all setup and it just works.
Running a Linux VM to de-clutter my main system and ran into this issue too.

Some Google-Fu and looks like this is a common issue for SQLite Databases (and others) via smb/samba/cifs/nfs etc... I actually don't even think there is anything the mighty Jules can do to fix it, BUT, I found some articles to help.

For me at least (using CIFS and SMB3) you need to enable a "No Lock"/`nobrl`option when mounting. Either added to your /etc/fstab file (if using that) or to the command you launch it with:

fstab example:
`\\192.168.#.#\ShareName /mnt/MountedShare cifs username=**,password=**,iocharset=utf8,**nobrl**,file_mode=###,dir_mode=### 0 0`

`sudo mount -a` then remounts/reloads your fstab file without needing to reboot

**Comment by C-BoT-AU** [comment]
References:
https://blog.archiware.com/blog/pure_forum/pure-question-answers/database-is-locked/
https://forum.archive.openwrt.org/viewtopic.php?id=32812
https://github.com/bcbio/bcbio-nextgen/issues/1123
https://sqlite-users.sqlite.narkive.com/8aUfXuBy/sqlite-db-is-locked-on-network-drive
