### ISSUE TITLE
[BUG] Donwloading Issue still persist. 

### ISSUE THREAD

**Issue by umbraburn21** [Jules-WinnfieldX/CyberDropDownloader#332]
Still getting this error after the recent update to 4.0.4

Starting Cyberdrop-DL
We are running version 4.0.4 of Cyberdrop Downloader
Starting Scrape
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Scripts\cyberdrop-dl.exe_main.py", line 7, in
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 233, in main
loop.run_until_complete(director(args, links))
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 185, in director
Cascade, Forums = await scrape_links(Scraper, links)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 156, in scrape_links
await asyncio.wait(tasks)
File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 415, in wait
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'ScrapeMapper.map_url' was never awaited

C:\Users\casht\Downloads\Compressed\Cyberdrop_DL.V3>pause
Press any key to continue . . .

**Comment by Jules-WinnfieldX** [comment]
Just released 4.0.5, please update and try again. Tell me if it's working.

**Comment by umbraburn21** [comment]
Updated and its working now. Thanks for the fast response and fix.
