### ISSUE TITLE
[BUG] Can't scrape simpcity threads

### ISSUE THREAD

**Issue by jankintu** [Jules-WinnfieldX/CyberDropDownloader#339]
**Describe the bug**
Can't scrape simpcity threads

**To Help Reproduce**

- Version: 4.0.31
- config.yaml for storing simpcity creds
- URLs.txt for list of threads

Example:
URLs.txt
```
https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/
https://simpcity.su/threads/princesslilmary-princess-mary.18407/
```

**Screenshots**
```
Starting Cyberdrop-DL
We are running version 4.0.31 of Cyberdrop Downloader
Starting Scrape
Starting: https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/
Error: https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/
Starting: https://simpcity.su/threads/princesslilmary-princess-mary.18407/
Error: https://simpcity.su/threads/princesslilmary-princess-mary.18407/
Finished Scrape

Sorting Downloads
Organized: 0 Audio Files
Organized: 0 Image Files
Organized: 0 Video Files
Organized: 0 Other Files

Checking for incomplete downloads
Purging empty directories
Finished downloading. Enjoy :)
There are partial downloads in the downloads folder.

If you enjoy using this program, please consider buying the developer a coffee :)
https://www.buymeacoffee.com/juleswinnft
```

**Setup Information**
 - OS: Debian GNU/Linux 9 (stretch)
 - Cyberdrop Downloader Version # 4.0.31

**Downloader.log file**
```
2023-02-18 07:03:58,664:DEBUG:selector_events:selector_events.py:59:Using selector: EpollSelector
2023-02-18 07:03:58,669:DEBUG:base_functions:base_functions.py:46:Starting Cyberdrop-DL
2023-02-18 07:03:58,673:DEBUG:base_functions:base_functions.py:46:Using authentication arguments: {'pixeldrain_api_key': '!REDACTED!', 'simpcity_password': '!REDACTED!', 'simpcity_username': '!REDACTED!', 'socialmediagirls_password': '!REDACTED!', 'socialmediagirls_username': '!REDACTED!', 'xbunker_password': '!REDACTED!', 'xbunker_username': '!REDACTED!'}
2023-02-18 07:03:58,673:DEBUG:base_functions:base_functions.py:46:Using file arguments: {'db_file': PosixPath('download_history.sqlite'), 'errored_urls_file': PosixPath('Errored_URLs.csv'), 'input_file': PosixPath('URLs.txt'), 'log_file': PosixPath('downloader.log'), 'output_folder': PosixPath('Downloads'), 'output_last_forum_post_file': PosixPath('URLs_last_post.txt'), 'unsupported_urls_file': PosixPath('Unsupported_URLs.csv')}
2023-02-18 07:03:58,673:DEBUG:base_functions:base_functions.py:46:Using forum option arguments: {'output_last_forum_post': False, 'separate_posts': False}
2023-02-18 07:03:58,673:DEBUG:base_functions:base_functions.py:46:Using ignore arguments: {'exclude_audio': True, 'exclude_images': False, 'exclude_other': False, 'exclude_videos': False, 'ignore_cache': False, 'ignore_history': True, 'skip_hosts': []}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:Using jdownloader arguments: {'apply_jdownloader': False, 'jdownloader_device': 'JDownloader@!REDACTED!', 'jdownloader_password': '!REDACTED!', 'jdownloader_username': '!REDACTED!'}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:Using progress option arguments: {'dont_show_album_progress': False, 'dont_show_domain_progress': False, 'dont_show_file_progress': False, 'dont_show_forum_progress': False, 'dont_show_overall_progress': False, 'dont_show_thread_progress': False, 'hide_new_progress': False}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:Using ratelimiting arguments: {'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:Using runtime arguments: {'allow_insecure_connections': False, 'attempts': 10, 'block_sub_folders': False, 'disable_attempt_limit': False, 'include_id': False, 'output_errored_urls': False, 'output_unsupported_urls': False, 'proxy': '', 'remove_bunkr_identifier': True, 'required_free_space': 5, 'simultaneous_downloads_per_domain': 5, 'skip_download_mark_completed': False}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:Using sorting arguments: {'sort_directory': PosixPath('Sorted Downloads'), 'sort_downloads': True, 'sorted_audio': '{sort_dir}/{base_dir}/Audio', 'sorted_images': '{sort_dir}/{base_dir}/Images', 'sorted_others': '{sort_dir}/{base_dir}/Other', 'sorted_videos': '{sort_dir}/{base_dir}/Videos'}
2023-02-18 07:03:58,674:DEBUG:base_functions:base_functions.py:46:We are running version 4.0.31 of Cyberdrop Downloader
2023-02-18 07:03:58,695:DEBUG:base_functions:base_functions.py:46:[green]Starting Scrape[/green]
2023-02-18 07:03:58,696:DEBUG:base_functions:base_functions.py:46:[green]Starting: https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/[/green]
2023-02-18 07:03:58,872:DEBUG:Xenforo_Spider:Xenforo_Spider.py:100:Error encountered while handling https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/
Traceback (most recent call last):
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 90, in fetch
    await self.simpcity.login(session, url, self.quiet)
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 44, in login
    await session.post_data_no_resp(domain / "login", data=data)
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 104, in post_data_no_resp
    async with self.client_session.post(url, data=data, headers=self.headers, ssl=self.client.ssl_context) as response:
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://simpcity.su/login/login')
2023-02-18 07:03:58,874:DEBUG:base_functions:base_functions.py:46:[red]Error: https://simpcity.su/threads/stefanie-knight-gurzanski-stefbabyg.10493/[/red]
2023-02-18 07:03:58,875:DEBUG:Xenforo_Spider:Xenforo_Spider.py:102:403, message='Forbidden', url=URL('https://simpcity.su/login/login')
2023-02-18 07:03:58,876:DEBUG:base_functions:base_functions.py:46:[green]Starting: https://simpcity.su/threads/princesslilmary-princess-mary.18407/[/green]
2023-02-18 07:03:58,954:DEBUG:Xenforo_Spider:Xenforo_Spider.py:100:Error encountered while handling https://simpcity.su/threads/princesslilmary-princess-mary.18407/
Traceback (most recent call last):
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 91, in fetch
    title = await self.parse_simpcity(session, scrape_url, cascade, "", post_num)
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 195, in parse_simpcity
    soup = await session.get_BS4(url)
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 50, in get_BS4
    async with self.client_session.get(url, ssl=self.client.ssl_context) as response:
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/NAME/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://simpcity.su/threads/princesslilmary-princess-mary.18407/')
2023-02-18 07:03:58,955:DEBUG:base_functions:base_functions.py:46:[red]Error: https://simpcity.su/threads/princesslilmary-princess-mary.18407/[/red]
2023-02-18 07:03:58,956:DEBUG:Xenforo_Spider:Xenforo_Spider.py:102:403, message='Forbidden', url=URL('https://simpcity.su/threads/princesslilmary-princess-mary.18407/')
2023-02-18 07:03:58,957:DEBUG:base_functions:base_functions.py:46:[green]Finished Scrape[/green]
2023-02-18 07:04:03,967:DEBUG:base_functions:base_functions.py:46:
2023-02-18 07:04:03,969:DEBUG:base_functions:base_functions.py:46:Sorting Downloads
2023-02-18 07:04:08,974:DEBUG:base_functions:base_functions.py:46:[green]Organized: 0 Audio Files[/green]
2023-02-18 07:04:08,976:DEBUG:base_functions:base_functions.py:46:[green]Organized: 0 Image Files[/green]
2023-02-18 07:04:08,976:DEBUG:base_functions:base_functions.py:46:[green]Organized: 0 Video Files[/green]
2023-02-18 07:04:08,977:DEBUG:base_functions:base_functions.py:46:[green]Organized: 0 Other Files[/green]
2023-02-18 07:04:08,978:DEBUG:base_functions:base_functions.py:46:
2023-02-18 07:04:08,978:DEBUG:base_functions:base_functions.py:46:Checking for incomplete downloads
2023-02-18 07:04:08,979:DEBUG:base_functions:base_functions.py:46:Purging empty directories
2023-02-18 07:04:08,980:DEBUG:base_functions:base_functions.py:46:Finished downloading. Enjoy :)
2023-02-18 07:04:08,980:DEBUG:base_functions:base_functions.py:46:[yellow]There are partial downloads in the downloads folder.[/yellow]
2023-02-18 07:04:08,981:DEBUG:base_functions:base_functions.py:46:
2023-02-18 07:04:08,981:DEBUG:base_functions:base_functions.py:46:[green]If you enjoy using this program, please consider buying the developer a coffee :)
https://www.buymeacoffee.com/juleswinnft
2023-02-18 07:04:13,988:DEBUG:sql_helper:sql_helper.py:228:Successfully closed sqlite database connection

```

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
This isn't an error with Cyberdrop-DL, it's an error with Simpcity and their login page. It'll sort itself out over time.

**Comment by Jules-WinnfieldX** [comment]
4.0.33 should address the new ratelimit during login

**Comment by jankintu** [comment]
confirmed using v4.0.34
thanks
