### ISSUE TITLE
[BUG] nsfw.xxx http 500 errors

### ISSUE THREAD

**Issue by slitchampion** [Jules-WinnfieldX/CyberDropDownloader#415]
**Describe the bug**
nsfw.xxx scraper running into http 500 errors.

**To Help Reproduce**
enter a nsfw.xxx user url into URLs.txt: https://nsfw.xxx/user/altisalt/

```
023-04-09 06:10:29,796:DEBUG:NSFWXXXCrawler:NSFWXXXCrawler.py:50:Error encountered while handling https://nsfw.xxx/user/altisalt/
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/cyberdrop_dl/crawlers/NSFWXXXCrawler.py", line 36, in get_user
    page_soup = await session.get_BS4(page_url)
  File "/home/user/.local/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 51, in get_BS4
    async with self.client_session.get(url, ssl=self.client.ssl_context) as response:
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://nsfw.xxx/page/1?nsfw%5B%5D=0&types%5B%5D=image&types%5B%5D=video&types%5B%5D=gallery&slider=1&jsload=1&user=')
```

**Setup Information**
 - OS: Ubuntu 22.04
 - Cyberdrop Downloader Version 4.1.01

**Comment by Jules-WinnfieldX** [comment]
Will be fixed in next release. It's because you put the / at the end of the url.
