### ISSUE TITLE
Bunkr.la links say "403 forbidden"

### ISSUE THREAD

**Issue by notjustanygeek** [Jules-WinnfieldX/CyberDropDownloader#425]
I am scraping some bunkr.la albums today and yesterday, but today the script is not able to successfully scrape the content. I am running version 4.1.11. The download log, in its entirety is the following:

```
2023-04-15 12:35:45,610:DEBUG:proactor_events:proactor_events.py:625:Using proactor: IocpProactor
2023-04-15 12:35:45,628:DEBUG:base_functions:base_functions.py:51:Starting Cyberdrop-DL
2023-04-15 12:35:45,628:DEBUG:base_functions:base_functions.py:51:Using authentication arguments: {'gofile_api_key': '', 'pixeldrain_api_key': '!REDACTED!', 'simpcity_username': 'InspectorSimp', 'simpcity_password': '!REDACTED!', 'socialmediagirls_username': '', 'socialmediagirls_password': '!REDACTED!', 'xbunker_username': '', 'xbunker_password': '!REDACTED!'}
2023-04-15 12:35:45,628:DEBUG:base_functions:base_functions.py:51:Using file arguments: {'db_file': WindowsPath('download_history.sqlite'), 'errored_urls_file': WindowsPath('Errored_URLs.csv'), 'input_file': WindowsPath('URLs.txt'), 'log_file': WindowsPath('downloader.log'), 'output_folder': WindowsPath('D:/CyberDrop-DL Downloads'), 'output_last_forum_post_file': WindowsPath('URLs_last_post.txt'), 'unsupported_urls_file': WindowsPath('Unsupported_URLs.csv')}
2023-04-15 12:35:45,628:DEBUG:base_functions:base_functions.py:51:Using forum option arguments: {'output_last_forum_post': False, 'separate_posts': False}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using ignore arguments: {'exclude_videos': False, 'exclude_images': False, 'exclude_audio': False, 'exclude_other': False, 'ignore_cache': False, 'ignore_history': False, 'skip_hosts': [], 'only_hosts': []}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using jdownloader arguments: {'apply_jdownloader': False, 'jdownloader_username': '', 'jdownloader_password': '!REDACTED!', 'jdownloader_device': ''}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using progress option arguments: {'hide_new_progress': False, 'hide_overall_progress': False, 'hide_forum_progress': False, 'hide_thread_progress': False, 'hide_domain_progress': False, 'hide_album_progress': False, 'hide_file_progress': False, 'refresh_rate': 10}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using ratelimiting arguments: {'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using runtime arguments: {'allow_insecure_connections': True, 'attempts': 10, 'block_sub_folders': False, 'disable_attempt_limit': False, 'include_id': False, 'skip_download_mark_completed': False, 'output_errored_urls': False, 'output_unsupported_urls': False, 'proxy': '', 'remove_bunkr_identifier': False, 'required_free_space': 5, 'simultaneous_downloads_per_domain': 4}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:Using sorting arguments: {'sort_downloads': False, 'sort_directory': WindowsPath('Sorted Downloads'), 'sorted_audio': '{sort_dir}/{base_dir}/Audio', 'sorted_images': '{sort_dir}/{base_dir}/Images', 'sorted_others': '{sort_dir}/{base_dir}/Other', 'sorted_videos': '{sort_dir}/{base_dir}/Videos'}
2023-04-15 12:35:45,629:DEBUG:base_functions:base_functions.py:51:We are running version 4.1.11 of Cyberdrop Downloader
2023-04-15 12:35:45,737:DEBUG:base_functions:base_functions.py:51:Starting Scrape
2023-04-15 12:35:45,739:DEBUG:base_functions:base_functions.py:51:Starting: https://bunkr.la/a/jUT5aIau
2023-04-15 12:35:45,897:DEBUG:Bunkr_Spider:Bunkr_Spider.py:173:Error encountered while handling https://bunkr.la/a/jUT5aIau
Traceback (most recent call last):
  File "C:\Users\NicholasDurham\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\Bunkr_Spider.py", line 133, in get_album
    soup = await session.get_BS4(url)
  File "C:\Users\NicholasDurham\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\client\client.py", line 56, in get_BS4
    async with self.client_session.get(url, ssl=self.client.ssl_context) as response:
  File "C:\Users\NicholasDurham\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\NicholasDurham\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 643, in _request
    resp.raise_for_status()
  File "C:\Users\NicholasDurham\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://bunkr.la/a/jUT5aIau')
2023-04-15 12:35:45,898:DEBUG:base_functions:base_functions.py:51:Error: https://bunkr.la/a/jUT5aIau
2023-04-15 12:35:45,899:DEBUG:Bunkr_Spider:Bunkr_Spider.py:175:403, message='Forbidden', url=URL('https://bunkr.la/a/jUT5aIau')
2023-04-15 12:35:45,899:DEBUG:base_functions:base_functions.py:51:
2023-04-15 12:35:45,899:DEBUG:base_functions:base_functions.py:51:Finished Scrape

```

Any idea why this is happening?

**Comment by Jules-WinnfieldX** [comment]
Because of DDOS-Guard on their site. Nothing can be done about it. It'll either work again in a few days, or it won't.
