### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by poison696** [Jules-WinnfieldX/CyberDropDownloader#44]
hi i keep getting this error I checked url it start with https://www.  
URLs.txt exists
Traceback (most recent call last):
  File "C:\Users\Pakun\OneDrive\Desktop\CyberDropDownloader-2.1.5\main.py", line 74, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Pakun\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Pakun\OneDrive\Desktop\CyberDropDownloader-2.1.5\main.py", line 63, in main
    raise ValueError('No links found, check the URL.txt\nNote: This utility only supports album links, not direct links to pictures or videos.')
ValueError: No links found, check the URL.txt
Note: This utility only supports album links, not direct links to pictures or videos.

**Comment by poison696** [comment]
it works when i open vpn
