### ISSUE TITLE
[FEATURE] Collect errors during Scrape

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#457]
Consider the session with attached logs.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11410882/downloader.log)
[Errored_URLs.csv](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11410883/Errored_URLs.csv)

There were a few errors during Download phase, e.g.

```
2023-05-05 00:26:21,406:DEBUG:downloaders:downloaders.py:208:
https://simp4.jpg.fish/3840x2880_470ebcb9730461ed9a1b726193ae343d.jpg (Not Found)
2023-05-05 00:26:21,406:DEBUG:downloaders:downloaders.py:212:We ran into a 400 level error: 404
2023-05-05 00:26:21,406:DEBUG:base_functions:base_functions.py:51:Failed Download: 3840x2880_470ebcb9730461ed9a1b726193ae343d.jpg
```

this attempt was properly logged into `Errored_URLs.csv`:

```
https://simp4.jpg.fish/3840x2880_470ebcb9730461ed9a1b726193ae343d.jpg,https://jpg.church/img/gEgDre,Not Found
```

therefore, it looks like the errors during the Download phase are handled as expected. Once the tool exits, I can review the `Errored_URLs.csv` and know what's missing.

However, there were a few errors during the Scrape phase as well, e.g.

```
2023-05-05 00:11:14,914:DEBUG:PostImg_Spider:PostImg_Spider.py:38:Error encountered while handling https://i.postimg.cc/d1qrCNBV/D045-A25-F-005-B-4-F27-AFA7-A026-BC2-F9-CC1.jpg
Traceback (most recent call last):
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cyberdrop_dl\crawlers\PostImg_Spider.py", line 34, in fetch
    media_item = await self.get_singular(session, url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cyberdrop_dl\crawlers\PostImg_Spider.py", line 71, in get_singular
    soup = await session.get_BS4(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cyberdrop_dl\client\client.py", line 38, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cyberdrop_dl\client\client.py", line 73, in get_BS4
    raise InvalidContentTypeFailure(message=f"Received {content_type}, was expecting text")
cyberdrop_dl.base_functions.error_classes.InvalidContentTypeFailure: Received image/jpeg, was expecting text
2023-05-05 00:11:14,945:DEBUG:base_functions:base_functions.py:51:Error: https://i.postimg.cc/d1qrCNBV/D045-A25-F-005-B-4-F27-AFA7-A026-BC2-F9-CC1.jpg
2023-05-05 00:11:14,945:DEBUG:PostImg_Spider:PostImg_Spider.py:40:Received image/jpeg, was expecting text
2023-05-05 00:11:14,945:DEBUG:base_functions:base_functions.py:51:Finished: https://i.postimg.cc/d1qrCNBV/D045-A25-F-005-B-4-F27-AFA7-A026-BC2-F9-CC1.jpg
```

This error is only briefly displayed on the console during the Scrape phase. But unfortunately, this output gets overwritten soon by the Download progress. So, there's no easy way to notice those errors.

I would expect those errors to be logged, similarly to Download errors, either to `Errored_URLs.csv` or some other, dedicated file.

**Comment by Jules-WinnfieldX** [comment]
I will add this. Just need motivation/time for it.

**Comment by Jules-WinnfieldX** [comment]
Added in 4.2.32
