### ISSUE TITLE
[BUG]Issues related to --hide-new-progress Progress_Options config

### ISSUE THREAD

**Issue by vanminhle** [Jules-WinnfieldX/CyberDropDownloader#470]
**Describe the bug**
I want to start the CyberDrop Downloader with old progress system, When using `cyberdrop-dl --hide-new-progress` it throw an error `missing 1 required positional argument: 'error_writer'`

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Install the cyberdrop with `pip install cyberdrop-dl` and setup the URLs.txt
2. Add some GoFile links to URLs.txt and start cyberdrop with `cyberdrop-dl --hide-new-progress`

**Output**
```
Files Downloaded:   0% 0.00/3.00 [00:00<?, ?Files/s]
Traceback (most recent call last):
  File "/usr/local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/main.py", line 312, in main
    loop.run_until_complete(director(args, links))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/main.py", line 264, in director
    await old_download_forums(args, Forums, SQL_Helper, client)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/downloader/old_downloaders.py", line 281, in old_download_forums
    downloader = Old_Downloader(args, client, SQL_Helper, domain, domain_obj, files)
TypeError: Old_Downloader.__init__() missing 1 required positional argument: 'error_writer'

```

**Setup Information**
 - OS: Ubuntu 20.04.5 LTS
 - Cyberdrop Downloader Version 4.2.35

**Downloader.log file**
```
2023-05-20 02:41:43,325:DEBUG:selector_events:selector_events.py:54:Using selector: EpollSelector
2023-05-20 02:41:43,332:DEBUG:base_functions:base_functions.py:54:Starting Cyberdrop-DL
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using authentication arguments: {'gofile_api_key': '!REDACTED!', 'pixeldrain_api_key': '!REDACTED!', 'nudostar_username': '', 'nudostar_password': '!REDACTED!', 'simpcity_username': '', 'simpcity_password': '!REDACTED!', 'socialmediagirls_username': '', 'socialmediagirls_password': '!REDACTED!', 'xbunker_username': '', 'xbunker_password': '!REDACTED!'}
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using file arguments: {'db_file': PosixPath('download_history.sqlite'), 'errored_download_urls_file': PosixPath('Errored_Download_URLs.csv'), 'errored_scrape_urls_file': PosixPath('Errored_Scrape_URLs.csv'), 'input_file': PosixPath('URLs.txt'), 'log_file': PosixPath('downloader.log'), 'output_folder': PosixPath('Downloads'), 'output_last_forum_post_file': PosixPath('URLs_last_post.txt'), 'unsupported_urls_file': PosixPath('Unsupported_URLs.csv')}
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using forum option arguments: {'output_last_forum_post': False, 'scrape_single_post': False, 'separate_posts': False}
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using ignore arguments: {'exclude_videos': False, 'exclude_images': False, 'exclude_audio': False, 'exclude_other': False, 'ignore_cache': False, 'ignore_history': False, 'skip_hosts': [], 'only_hosts': []}
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using jdownloader arguments: {'apply_jdownloader': False, 'jdownloader_username': '', 'jdownloader_password': '!REDACTED!', 'jdownloader_device': ''}
2023-05-20 02:41:43,335:DEBUG:base_functions:base_functions.py:54:Using progress option arguments: {'hide_new_progress': True, 'hide_overall_progress': False, 'hide_forum_progress': False, 'hide_thread_progress': False, 'hide_domain_progress': False, 'hide_album_progress': False, 'hide_file_progress': False, 'refresh_rate': 10, 'visible_rows_threads': 2, 'visible_rows_domains': 2, 'visible_rows_albums': 2, 'visible_rows_files': 10}
2023-05-20 02:41:43,336:DEBUG:base_functions:base_functions.py:54:Using ratelimiting arguments: {'connection_timeout': 15, 'ratelimit': 50, 'throttle': 0.5}
2023-05-20 02:41:43,336:DEBUG:base_functions:base_functions.py:54:Using runtime arguments: {'allow_insecure_connections': False, 'attempts': 10, 'block_sub_folders': False, 'disable_attempt_limit': False, 'include_id': False, 'max_concurrent_threads': 0, 'max_concurrent_domains': 0, 'max_concurrent_albums': 0, 'max_concurrent_downloads_per_domain': 4, 'output_errored_urls': False, 'output_unsupported_urls': False, 'proxy': '', 'remove_bunkr_identifier': False, 'required_free_space': 5, 'skip_download_mark_completed': False, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0'}
2023-05-20 02:41:43,336:DEBUG:base_functions:base_functions.py:54:Using sorting arguments: {'sort_downloads': False, 'sort_directory': PosixPath('Sorted Downloads'), 'sorted_audio': '{sort_dir}/{base_dir}/Audio', 'sorted_images': '{sort_dir}/{base_dir}/Images', 'sorted_others': '{sort_dir}/{base_dir}/Other', 'sorted_videos': '{sort_dir}/{base_dir}/Videos'}
2023-05-20 02:41:43,336:DEBUG:base_functions:base_functions.py:54:We are running version 4.2.35 of Cyberdrop Downloader
2023-05-20 02:41:43,350:DEBUG:base_functions:base_functions.py:54:Starting Scrape
2023-05-20 02:41:44,115:DEBUG:base_functions:base_functions.py:54:Starting: https://gofile.io/d/xxxxxx
2023-05-20 02:41:45,299:DEBUG:base_functions:base_functions.py:54:Finished: https://gofile.io/d/xxxxxx
2023-05-20 02:41:46,728:DEBUG:base_functions:base_functions.py:54:
2023-05-20 02:41:46,729:DEBUG:base_functions:base_functions.py:54:Finished Scrape
2023-05-20 02:41:51,744:DEBUG:sql_helper:sql_helper.py:281:Successfully closed sqlite database connection
```

**Additional context**
None

**Comment by Jules-WinnfieldX** [comment]
Should be fixed in 4.2.37
