### ISSUE TITLE
[BUG] Direct links to giant.gfycat.com error

### ISSUE THREAD

**Issue by smurf-beep** [Jules-WinnfieldX/CyberDropDownloader#482]
**Describe the bug**
When you call cyberdrop-dl on a giant.gfycat link, it will error out, similar error to #481.

**To Help Reproduce**
1. Call `cyberdrop-dl https://giant.gfycat.com/OccasionalIncompleteBunting.mp4` (NSFW)
2. Will error out

**Setup Information**
 - OS: Linux
 - Cyberdrop Downloader Version 4.2.52

**Downloader.log file**
```
2023-05-29 09:24:08,890:DEBUG:Gfycat_Spider:Gfycat_Spider.py:48:Error encountered while handling https://giant.gfycat.com/MintyJoyfulBlueandgoldmackaw.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Gfycat_Spider.py", line 28, in fetch
    soup = await session.get_BS4(url)
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 40, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 75, in get_BS4
    raise InvalidContentTypeFailure(message=f"Received {content_type}, was expecting text")
cyberdrop_dl.base_functions.error_classes.InvalidContentTypeFailure: Received video/mp4, was expecting text
2023-05-29 09:24:08,890:DEBUG:base_functions:base_functions.py:54:Error: https://giant.gfycat.com/MintyJoyfulBlueandgoldmackaw.mp4
2023-05-29 09:24:08,890:DEBUG:base_functions:base_functions.py:135:Received video/mp4, was expecting text
2023-05-29 09:24:08,893:DEBUG:Gfycat_Spider:Gfycat_Spider.py:48:Error encountered while handling https://giant.gfycat.com/MetallicDentalKilldeer.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Gfycat_Spider.py", line 28, in fetch
    soup = await session.get_BS4(url)
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 40, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 75, in get_BS4
    raise InvalidContentTypeFailure(message=f"Received {content_type}, was expecting text")
cyberdrop_dl.base_functions.error_classes.InvalidContentTypeFailure: Received video/mp4, was expecting text
```

**Comment by Jules-WinnfieldX** [comment]
This wasn't explicitly supported in the supported sites table (see wiki), but I've added handling for this in 4.2.53
