### ISSUE TITLE
[BUG]Bug related to old downloader feature (--hide-new-progress) config

### ISSUE THREAD

**Issue by vanminhle** [Jules-WinnfieldX/CyberDropDownloader#489]
**Describe the bug**
When using `cyberdrop-dl --hide-new-progress` it throw an error `KeyError: 'filesize_minimum_images'`

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Install the cyberdrop with `pip install cyberdrop-dl` and setup the URLs.txt
2. Add some GoFile links to URLs.txt and start cyberdrop with `cyberdrop-dl --hide-new-progress`

**Output**
```
Files Downloaded:   0% 0.00/1.00 [00:00<?, ?Files/s]
Traceback (most recent call last):
  File "/usr/local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/main.py", line 321, in main
    loop.run_until_complete(director(args, links))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/main.py", line 272, in director
    await old_download_forums(args, Forums, SQL_Helper, client, error_writer)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/downloader/old_downloaders.py", line 328, in old_download_forums
    downloader = Old_Downloader(args, client, SQL_Helper, domain, domain_obj, files, error_writer)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/downloader/old_downloaders.py", line 89, in __init__
    self.filesize_minimum_images = args["Ignore"]["filesize_minimum_images"]
KeyError: 'filesize_minimum_images'
```

**Setup Information**
 - OS: Ubuntu 20.04.5 LTS
 - Cyberdrop Downloader Version 4.2.71

**Describe the solution you'd like**
File path: cyberdrop_dl/downloader/old_downloaders.py
Section: Filesize limits (89-94)
Edit To: 
```
self.filesize_minimum_images = args["Runtime"]["filesize_minimum_images"]
self.filesize_minimum_videos = args["Runtime"]["filesize_minimum_videos"]
self.filesize_minimum_other = args["Runtime"]["filesize_minimum_other"]
self.filesize_maximum_images = args["Runtime"]["filesize_maximum_images"]
self.filesize_maximum_videos = args["Runtime"]["filesize_maximum_videos"]
self.filesize_maximum_other = args["Runtime"]["filesize_maximum_other"]
```
Description: The key should be Runtime, not Ignore

**Additional context**
None

**Comment by Jules-WinnfieldX** [comment]
4.2.72 makes this change
