### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SnapCrackerJack** [Jules-WinnfieldX/CyberDropDownloader#495]
This pops up at the end of the download, sometimes its longer:

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000139152AD1B0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Have reinstalled python, it didn't help, would not like to reinstall downloader if unnecessary

**Comment by Jules-WinnfieldX** [comment]
This error can be ignored currently.
