### ISSUE TITLE
[BUG] Event Loop Close

### ISSUE THREAD

**Issue by junjuiceee** [Jules-WinnfieldX/CyberDropDownloader#508]
Getting this bug when running. Program hangs for a while after starting to download files, gets a few files in, then produces this. PIP is fully upgraded, and plenty of space on the drive.

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C80C0011B0>
Traceback (most recent call last):
  File "C:\Users\12121212\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\12121212\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\12121212\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\12121212\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the entire downloader.log file

**Comment by junjuiceee** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12009867/downloader.log)

**Comment by junjuiceee** [comment]
Let me know if I need to do any extra redactions. I left it as is

**Comment by junjuiceee** [comment]
Thank you so so much. I really appreciate you taking a look at that for me. 

I'll send over a coffee donation. Thanks again!

**Comment by Jules-WinnfieldX** [comment]
Much appreciated! I'll try and get that sorted soon

**Comment by junjuiceee** [comment]
Thanks for making this thing virually stupid proof. Much appreciated. 

enjoy the coffees
