### ISSUE TITLE
[BUG] Issue with bug fix #509 - clean-up process hangs

### ISSUE THREAD

**Issue by SethBodine** [Jules-WinnfieldX/CyberDropDownloader#517]
**Describe the bug**

When executing with the new argument ```--skip-check-for-partial-files-and-empty-dirs``` additional errors are being seen at the end of processing

**To Help Reproduce**

Execute with new argument being included and it appears that the job hang during clean-up

```
322         if not args['Runtime']['skip_check_for_partial_files_and_empty_dirs']:
```

**Setup Information**
    OS: Ubuntu
    Deployment: git clone https://github.com/Jules-WinnfieldX/CyberDropDownloader.git
    Python: v3 with virtualenv
    exe: python3 start.py
    version: 4.2.137

**Downloader.log file**
```
<snip>

2023-07-14 10:24:28,020:DEBUG:base_functions:base_functions.py:60:| [green]Files Complete: 0[/green] - [yellow]Files Skipped:  70[/yellow] - [red]Files Failed: 0[/red] |
2023-07-14 10:24:28,022:DEBUG:base_functions:base_functions.py:60:
2023-07-14 10:24:28,023:ERROR:base_events:base_events.py:1744:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /opt/CyberDropDownloader/venv/lib/python3.10/site-packages/aiorun.py:209> exception=KeyError('skip_check_for_partial_files_and_empty_dirs')>
Traceback (most recent call last):
  File "/opt/CyberDropDownloader/venv/lib/python3.10/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/opt/CyberDropDownloader/cyberdrop_dl/main.py", line 322, in director
    if not args['Runtime']['skip_check_for_partial_files_and_empty_dirs']:
KeyError: 'skip_check_for_partial_files_and_empty_dirs'

# Ctrl + C pressed at this point after several minutes

2023-07-14 10:26:37,919:DEBUG:aiorun:aiorun.py:392:Entering shutdown handler
2023-07-14 10:26:37,919:WARNING:aiorun:aiorun.py:395:Stopping the loop
2023-07-14 10:26:37,920:INFO:aiorun:aiorun.py:263:Entering shutdown phase.
2023-07-14 10:26:37,920:INFO:aiorun:aiorun.py:359:Waiting for executor shutdown.
2023-07-14 10:26:37,921:INFO:aiorun:aiorun.py:363:Shutting down async generators
2023-07-14 10:26:37,921:INFO:aiorun:aiorun.py:365:Closing the loop.
2023-07-14 10:26:37,922:INFO:aiorun:aiorun.py:367:Leaving. Bye!
2023-07-14 10:26:37,923:DEBUG:sql_helper:sql_helper.py:281:Successfully closed sqlite database connection

</snip>
```
**Additional context**
Possibly bug introduced as part of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/509 fix

**Comment by Jules-WinnfieldX** [comment]
I can't recreate this, I'd recommend re-cloning the repository if you insist on running it as such, but you should seriously consider just using the package version of the program if you aren't editing any of the source files.
