### ISSUE TITLE
[BUG] ValueError: Invalid IPv6 URL on a malformed link ends the scraper

### ISSUE THREAD

**Issue by the444xg** [Jules-WinnfieldX/CyberDropDownloader#544]
**Describe the bug**
When scraping a malformed link recognized as an invalid ipv6 url it finishs the scraper and ends the script. 
It should just print/log the error and move on.

**To Help Reproduce**
Steps to help reproduce the behavior:
When trying to parse the malformed link (html below) the scrape is finished.

**Screenshots**
`
<a href="http://[URL='https://jpg.example/img/WwXh4I'][IMG alt=&quot;Screenshot_20220617-2341322.md.png&quot;]https://s.jpg.example/images/Screenshot_20220617-2341322.md.png[/IMG]" target="_blank" class="link link--external" rel="noopener">http://[URL='https://jpg.example/img...ages/Screenshot_20220617-2341322.md.png[/IMG]</a>
`

**Setup Information**
 - OS: Ubuntu 22
 - Cyberdrop Downloader Version 4.2.181

**Downloader.log file**
`
2023-08-11 10:03:46,133:DEBUG:base_functions:base_functions.py:60:We are running version 4.2.181 of Cyberdrop Downloader
2023-08-11 10:03:46,184:DEBUG:base_functions:base_functions.py:60:Starting Scrape
2023-08-11 10:03:46,185:DEBUG:base_functions:base_functions.py:60:Starting: !REDACTED!
2023-08-11 10:03:48,422:DEBUG:Xenforo_Spider:Xenforo_Spider.py:209:Error encountered while handling !REDACTED!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 207, in fetch
    title = await self.parse_forum(session, scrape_url, parse_spec, cascade, "", post_num)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 355, in parse_forum
    content_links.extend([(URL(link), temp_title) for link in links])
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 355, in <listcomp>
    content_links.extend([(URL(link), temp_title) for link in links])
  File "/usr/local/lib/python3.10/dist-packages/yarl/_url.py", line 172, in __new__
    val = urlsplit(val)
  File "/usr/lib/python3.10/urllib/parse.py", line 495, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
2023-08-11 10:03:48,423:DEBUG:base_functions:base_functions.py:60:Error: !REDACTED!
2023-08-11 10:03:48,424:DEBUG:base_functions:base_functions.py:180:Invalid IPv6 URL
2023-08-11 10:03:48,424:DEBUG:base_functions:base_functions.py:60:
2023-08-11 10:03:48,424:DEBUG:base_functions:base_functions.py:60:Finished Scrape
2023-08-11 10:03:53,436:DEBUG:base_functions:base_functions.py:60:
2023-08-11 10:03:53,436:DEBUG:base_functions:base_functions.py:60:Finished downloading. Enjoy :)
2023-08-11 10:03:55,774:ERROR:base_events:base_events.py:1758:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6abc801a20>
2023-08-11 10:03:55,775:ERROR:base_events:base_events.py:1758:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f6abb725960>, 174575.798020155)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f6abc801c30>
2023-08-11 10:03:55,775:DEBUG:base_functions:base_functions.py:60:
If you enjoy using this program, please consider buying the developer a coffee :)
https://www.buymeacoffee.com/juleswinnft
2023-08-11 10:03:55,776:INFO:aiorun:aiorun.py:263:Entering shutdown phase.
2023-08-11 10:03:55,776:INFO:aiorun:aiorun.py:359:Waiting for executor shutdown.
2023-08-11 10:03:55,776:INFO:aiorun:aiorun.py:363:Shutting down async generators
2023-08-11 10:03:55,777:INFO:aiorun:aiorun.py:365:Closing the loop.
2023-08-11 10:03:55,777:INFO:aiorun:aiorun.py:367:Leaving. Bye!
2023-08-11 10:03:55,778:DEBUG:sql_helper:sql_helper.py:281:Successfully closed sqlite database connection
`

**Comment by Jules-WinnfieldX** [comment]
In V5
