### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mikashina** [Jules-WinnfieldX/CyberDropDownloader#572]
When an invalid link is included in a page, the page terminates abnormally as an error.
Please recover to skip the invalid link and continue processing.
```

2023-09-09 12:09:27,578:DEBUG:base_functions:base_functions.py:60:Starting: https://simpcity.su/threads/ayachamo_1028.17264/post-1591031

2023-09-09 12:09:50,403:DEBUG:Xenforo_Spider:Xenforo_Spider.py:196:Error encountered while handling https://simpcity.su/threads/ayachamo_1028.17264/post-1591031

Traceback (most recent call last):

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 194, in fetch

    title = await self.parse_forum(session, scrape_url, parse_spec, cascade, "", post_num)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 372, in parse_forum

    await self.parse_forum(session, next_page, spec, cascade, title, post_number)

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 372, in parse_forum

    await self.parse_forum(session, next_page, spec, cascade, title, post_number)

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 342, in parse_forum

    content_links.extend([(URL(link), temp_title) for link in links])

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 342, in <listcomp>

    content_links.extend([(URL(link), temp_title) for link in links])

                           ^^^^^^^^^

  File "C:\Users\piyohoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\yarl\_url.py", line 172, in __new__
``
```
whoever made that post put in a link like: http://Long Legs Aya-chan [i_kFNUFF3NI]

**Comment by Jules-WinnfieldX** [comment]
In V5
