### ISSUE TITLE
[BUG] 0 of 0 files for any download 

### ISSUE THREAD

**Issue by RazeBerry** [Jules-WinnfieldX/CyberDropDownloader#644]
**Describe the bug**
For any download operation no matter what website, it always display 0 of 0 file downloaded and making no progress whatsoever.

Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Described above to recreate the bug 
<img width="570" alt="Screenshot 2023-12-03 at 22 26 38" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/28079152/5ff9376e-fd3b-4a66-8a98-b61feffaa016">

**Screenshots**

**Setup Information**
 - OS: MacOs
 - Cyberdrop Downloader v5

**Comment by Jules-WinnfieldX** [comment]
The URLs file has changed. Try editing through the UI.

**Comment by RazeBerry** [comment]
@Jules-WinnfieldX Sorry I should have clarified, this applies equally when I use both CLI arguments and the UI url download. I edited it, saved it, pressed download, and it is still like this.

**Comment by RazeBerry** [comment]
<img width="385" alt="Screenshot 2023-12-03 at 22 32 42" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/28079152/f1d5c6c1-72d5-4ec7-9527-6238c8262f77">

CLI: cyberdrop-dl --download https://pixeldrain.com/l/sEQFDXDE for example

**Comment by KaraokeKev** [comment]
> same here, the fix is not working for me (tried on popOS 22.04, debian 5, unraid 6.12 )
> 
> cyberdrop-dl --download https://pixeldrain.com/l/sEQFDXDE Unhandled exception; stopping loop: 'Task exception was never retrieved' Traceback (most recent call last): File "/usr/lib64/python3.9/site-packages/cyberdrop_dl/scraper/scraper.py", line 323, in map_urls scrape_item: ScrapeItem = await self.manager.queue_manager.url_objects_to_map.get() File "/usr/lib64/python3.9/asyncio/queues.py", line 166, in get await getter RuntimeError: Task <Task pending name='Task-2' coro=<ScrapeMapper.map_urls() running at /usr/lib64/python3.9/site-packages/cyberdrop_dl/scraper/scraper.py:323>> got Future attached to a different loop
> 
> │ Completed 0 of 0 Files Com… │ Previously Downloa… 0 of 0 Files Com… │ Skipped By Configu… 0 of 0 Files Com… │ Failed 0 of 0 Files Com…

This is the same error I am seeing on MacOS 14.1.1

**Comment by V-i-K-M** [comment]
Have the same problem.
Update was installed today but the links are not downloading
Win11
Tried bunkrr.su & pixeldrain.com

**Comment by KaraokeKev** [comment]
> @V-i-K-M @KaraokeKev @rj-d2
> 
> I'm dropping support for python below 3.10.
> 
> You can see how to update to 3.10 or newer (don't use 3.12) here: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start
> 
> If you want to revert to V4 of cyberdrop-dl you can see how to do that here: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/frequently-asked-questions#how-do-i-go-back-to-v4
> 
> As for the error message about poetry, I forgot to take out that line in the start file, grab a new zip. It should be fixed.

Switching over to pip 3.10 and upgrading solved this issue for me.
