### ISSUE TITLE
Import error libgl

### ISSUE THREAD

**Issue by N30Z3N** [Jules-WinnfieldX/CyberDropDownloader#645]
After running first time blank cyberdrop-dl this occured

```
Traceback (most recent call last):
  File "/root/venv/bin/cyberdrop-dl", line 5, in <module>
    from cyberdrop_dl.main import main
  File "/root/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 14, in <module>
    from cyberdrop_dl.utils.sorting import Sorter
  File "/root/venv/lib/python3.11/site-packages/cyberdrop_dl/utils/sorting.py", line 6, in <module>
    import cv2
  File "/root/venv/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/venv/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

 - OS: linux debian
 - Cyberdrop Downloader Version # 5

**Comment by Jules-WinnfieldX** [comment]
try `apt-get update && apt-get install libgl1` and see that fixes it for you

**Comment by N30Z3N** [comment]
yeah running good what about failed files is there way to download them again without dupes ?

**Comment by N30Z3N** [comment]
> yeah running good what about failed files is there way to download them again without dupes ? I ran that option retry failed downloads but it says finished anyway I can edit waiting time for the downloader

I tried Editing Rate Limiting Settings
? Connection Timeout (in seconds): 80 . 0
Input should be a number

this is the output

**Comment by Jules-WinnfieldX** [comment]
The issue updating config values is fixed in the newest version :)
