### ISSUE TITLE
[BUG] cannot edit User Agent in 5.0 

### ISSUE THREAD

**Issue by Maqiic** [Jules-WinnfieldX/CyberDropDownloader#648]
**Describe the bug**
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately.

When trying to edit the user agent from the Global Settings Menu, after pressing enter do save following Output is generated: 

Editing General Settings
? Allow insecure connections? Yes
? User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
? Proxy: 
? Max Filename Length: 95
Traceback (most recent call last):
  File "/opt/homebrew/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 101, in main
    manager = startup()
              ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 30, in startup
    program_ui(manager)
  File "/opt/homebrew/lib/python3.11/site-packages/cyberdrop_dl/ui/ui.py", line 103, in program_ui
    edit_global_settings_prompt(manager)
  File "/opt/homebrew/lib/python3.11/site-packages/cyberdrop_dl/ui/prompts/settings_global_prompts.py", line 32, in edit_global_settings_prompt
    edit_general_settings_prompt(manager)
  File "/opt/homebrew/lib/python3.11/site-packages/cyberdrop_dl/ui/prompts/settings_global_prompts.py", line 64, in edit_general_settings_prompt
    max_folder_name_length = inquirer.number(
                             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/InquirerPy/prompts/number.py", line 178, in __init__
    raise InvalidArgument(
InquirerPy.exceptions.InvalidArgument: NumberPrompt argument 'default' should return type of int

3. Provide an example album that showcases it (if applicable)
Not needed 
5. Make sure you are updated to the latest version to see if it's already fixed.
Already Version 5 --> Version: 5.0.14 

**Screenshots**

**Setup Information**
 - OS: MacBook Air M2 - 14.1.1  
 - Cyberdrop Downloader Version # Version: 5.0.14

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
5.0.16 going up now will fix both of those issues.
