### ISSUE TITLE
[BUG] KeyError: 'nudostar.com'

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#654]
I got

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\****\AppData\Local\Programs\Python\Python311\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
>   File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 108, in main
>     aiorun.run(director(manager), stop_on_unhandled_errors=True)
>   File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiorun.py", line 371, in run
>     raise pending_exception_to_raise
>   File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 364, in map_urls
>     await self.existing_crawlers[key].startup()
>           ~~~~~~~~~~~~~~~~~~~~~~^^^^^
> KeyError: 'nudostar.com'

and ctlr+C doesn't work

**Comment by Jules-WinnfieldX** [comment]
5.0.23 fixes the key error

Ctrl + C will have to come later.
