### ISSUE TITLE
[BUG] crash in `Delay between requests during the download stage`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#664]
I'm not trying to change anything (yet), just looking at what the defaults are. Hitting `Enter` all the time without inputting any values here.

```
Editing Rate Limiting Settings
? Connection Timeout (in seconds): 15.0
? Read Timeout (in seconds): 300.0
? Download Attempts: 10
? Maximum number of requests per second: 50
? Delay between requests during the download stage: 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 103, in main
    manager = startup()
              ^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 30, in startup
    program_ui(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\ui.py", line 122, in program_ui
    edit_global_settings_prompt(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\prompts\settings_global_prompts.py", line 36, in edit_global_settings_prompt
    edit_rate_limiting_settings_prompt(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\prompts\settings_global_prompts.py", line 125, in edit_rate_limiting_settings_prompt
    max_simultaneous_downloads = inquirer.text(
                                 ^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\InquirerPy\prompts\input.py", line 131, in __init__
    raise InvalidArgument(
InquirerPy.exceptions.InvalidArgument: InputPrompt argument 'default' should be type of str
PS C:\Mirror — Temp\cdl>
```

**Comment by Jules-WinnfieldX** [comment]
Looks like I missed a few more things. Fun fun.

**Comment by baccccccc** [comment]
yeah, the number of these crashes dramatically decreased in the last day :) There used to be so many of them I did not even bother filing bugs. But now it's almost working!

(hope you don't mind sarcasm, I really appreciate your job, I know shit happens and happy to help where I can.)

**Comment by Jules-WinnfieldX** [comment]
5.0.35 going up now will fix it. 

Someone's gotta point them out or they won't get fixed haha
