### ISSUE TITLE
[BUG] Cyberdrop-dl not working on version 5.0.35

### ISSUE THREAD

**Issue by marioaugustorama** [Jules-WinnfieldX/CyberDropDownloader#671]
When i update to latest version final .35 ocurred this error:

Traceback (most recent call last):
  File "/home/suporte/.local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 103, in main
    manager = startup()
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 26, in startup
    manager = Manager()
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/managers/manager.py", line 37, in __init__
    self.first_time_setup.startup()
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/utils/transfer/first_time_setup.py", line 40, in startup
    OLD_APP_STORAGE.rename(APP_STORAGE)
  File "/opt/python/3.10.0/lib/python3.10/pathlib.py", line 1232, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/home/suporte/.config/Cyberdrop-DL' -> 'AppData'

I Made a update using pip3 install --upgrade cyberdrop-dl

Running on:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by Jules-WinnfieldX** [comment]
Where are you running Cyberdrop-DL from?

**Comment by sirjackh** [comment]
Same issue here, seems to be from this commit where the dynamic paths changed to hardcoded ones : https://github.com/Jules-WinnfieldX/CyberDropDownloader/commit/e36071e3037c9d44f5886d27640a4b7d60fbcc0f

AppData is a windows thing, so it seems to cause error on Linux.

**Comment by Jules-WinnfieldX** [comment]
So the word appdata is causing some issues here in the discussion. Cyberdrop-DL is attempting to rename 

'/home/<User>/.config/Cyberdrop-DL' to be `./appdata` in whatever directory you are running CDL from. It's not trying to reference the actually windows appdata path.

**Comment by Jules-WinnfieldX** [comment]
You can do this move/rename yourself, and it'll solve the issue.

**Comment by Jules-WinnfieldX** [comment]
I just added a --appdata-folder argument. You can specify it to where it currently exists: `/home/<User>/.config/Cyberdrop-DL`

and it'll use that location. It also shouldn't attempt to move it.
