### ISSUE TITLE
[BUG] OSError: [Errno 18] Invalid cross-device link: '/home/daniel/.config/Cyberdrop-DL' -> 'AppData'

### ISSUE THREAD

**Issue by Auravendill** [Jules-WinnfieldX/CyberDropDownloader#672]
After updating to version 5.0.36 it just crashes with:

```
Traceback (most recent call last):
  File "/usr/local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cyberdrop_dl/main.py", line 103, in main
    manager = startup()
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cyberdrop_dl/main.py", line 26, in startup
    manager = Manager()
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cyberdrop_dl/managers/manager.py", line 37, in __init__
    self.first_time_setup.startup()
  File "/usr/local/lib/python3.11/dist-packages/cyberdrop_dl/utils/transfer/first_time_setup.py", line 40, in startup
    OLD_APP_STORAGE.rename(APP_STORAGE)
  File "/usr/lib/python3.11/pathlib.py", line 1176, in rename
    os.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/home/daniel/.config/Cyberdrop-DL' -> 'AppData'
```

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Install/Update current version via pip3 on Linux
2. Try to run it
3. Crash

**Setup Information**
 - OS: Debian 12
 - Cyberdrop Downloader Version 5.0.36

**Comment by Auravendill** [comment]
Imo this looks like something Windows specific also gets called in Linux, when it shouldn't.

**Comment by Jules-WinnfieldX** [comment]
That's potentially what's happening, though I don't know what to do to fix that code wise. 

what's happening is CDL (by popular demand) was told to move files out of appdata back to the directory that the user is running the program from. 

An easy fix here would be for you to move the `/home/daniel/.config/Cyberdrop-DL` folder to wherever you are running the program, and rename it `AppData`, then make sure that folder no longer exists in .config

**Comment by Jules-WinnfieldX** [comment]
Sounds good, glad it's running at least! If you can't figure it out open a new issue and we can try and sort it out when I get a chance
