### ISSUE TITLE
[BUG] Trying to extract a cookie from browser fails with `Permission denied`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#686]
Trying to extract a cookie from browser fails with `Permission denied` in case browser is running. This kinda makes sense if you think about it. But maybe it should not crash?

Instead, check whether you can access the file (and/or whether browser process is running), and return a graceful error message. Or, at very least, add a message before extraction attempt, instructing the user to close all browser windows (and kill remaining lingering processes!) 

```
Cyberdrop Downloader (V5.0.46)
Current Config: Default
? What would you like to do? Manage Configs
Manage Configs
Current Config: Default
? What would you like to do? Edit Authentication Values
Editing Authentication Values
? What would you like to do? Edit DDOS-Guard Cookies
Editing DDOS-Guard Cookie Values
? What would you like to do? Browser Cookie Extraction
? Which browser should we load cookies from? Edge
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 103, in main
    manager = startup()
              ^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 30, in startup
    program_ui(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\ui.py", line 118, in program_ui
    edit_authentication_values_prompt(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\prompts\settings_authentication_prompts.py", line 43, in edit_authentication_values_prompt
    edit_ddos_guard_cookies_prompt(manager)
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\prompts\settings_authentication_prompts.py", line 133, in edit_ddos_guard_cookies_prompt
    get_ddos_guard_cookies(manager, "edge")
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\args\browser_cookie_extraction.py", line 39, in get_ddos_guard_cookies
    cookie = get_cookie(browser, ddos_guard)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\args\browser_cookie_extraction.py", line 56, in get_cookie
    cookie = browser_cookie3.edge(domain_name=domain)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\browser_cookie3\__init__.py", line 1195, in edge
    return Edge(cookie_file, domain_name, key_file).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\browser_cookie3\__init__.py", line 489, in load
    with _DatabaseConnetion(self.cookie_file) as con:
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\browser_cookie3\__init__.py", line 349, in __enter__
    return self.get_connection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\browser_cookie3\__init__.py", line 383, in get_connection
    con = method()
          ^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\browser_cookie3\__init__.py", line 374, in __get_connection_legacy
    shutil.copyfile(self.__database_file, self.__temp_cookie_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.240.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\<redacted>\\AppData\\Roaming\\..\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies'
PS C:\Mirror — Temp\cdl>
```

**Comment by Jules-WinnfieldX** [comment]
Weird, as I've never had to close firefox, this seems like it might be an edge specific issue, or its the windows store python.

Can you check with a different browser?

**Comment by baccccccc** [comment]
note that re-launching the process elevated ("As administrator" in Windows) does **not** help, since the files are still locked. However, closing browser does help.

just beware that if you have [Startup boost](https://support.microsoft.com/help/5008117) feature enabled in Edge, then it's _always running_ by default. Therefore, to release the locks on the files you'll have to kill all the processes before running CDL: `Get-Process -Name 'msEdge' | Stop-Process`

**Comment by baccccccc** [comment]
> Can you check with a different browser?

ok, I will in a few hours

**Comment by baccccccc** [comment]
ok, so Firefox won't crash CDL indeed. However, both Edge and Chrome do crash it. So, it might be a Chromium thing?

**Comment by Jules-WinnfieldX** [comment]
You're probably right.
