### ISSUE TITLE
[BUG] Error when configure Correct path to Sorted Download: 5.0.53

### ISSUE THREAD

**Issue by marioaugustorama** [Jules-WinnfieldX/CyberDropDownloader#689]
When configure correct path to Sorted Downloads i got this error:

Traceback (most recent call last):
  File "/home/suporte/.local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 103, in main
    manager = startup()
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 30, in startup
    program_ui(manager)
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/ui/ui.py", line 114, in program_ui
    edit_config_values_prompt(manager)
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/ui/prompts/settings_user_prompts.py", line 84, in edit_config_values_prompt
    edit_sort_options_prompt(config)
  File "/home/suporte/.local/lib/python3.10/site-packages/cyberdrop_dl/ui/prompts/settings_user_prompts.py", line 358, in edit_sort_options_prompt
    default=config['Sorting']['sorted_audio_folder'],
KeyError: 'sorted_audio_folder'

**Comment by Jules-WinnfieldX** [comment]
Ahhh, lemme go fix that.

**Comment by Jules-WinnfieldX** [comment]
5.0.54 going up now should fix it.
