### ISSUE TITLE
[BUG] OS error when downloading a very long filename

### ISSUE THREAD

**Issue by dynbabaul** [Jules-WinnfieldX/CyberDropDownloader#71]
**Describe the bug**
When downloading a file that has a very long file name the OS throws an error and stops the download. Other files won't continue because of this error on this single file.

Traceback (most recent call last):
  File "/drives/spare01/x/dl/./main.py", line 92, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/drives/spare01/x/dl/./main.py", line 85, in main
    await downloader.download_content()
  File "/drives/spare01/x/dl/utils/downloaders.py", line 196, in download_content
    await self.download_all(self.links, session, headers=headers, show_progress=show_progress)
  File "/drives/spare01/x/dl/utils/downloaders.py", line 246, in download_all
    await super().download_all(links, session, headers=headers, show_progress=show_progress)
  File "/drives/spare01/x/dl/utils/downloaders.py", line 185, in download_all
    await func
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/drives/spare01/x/dl/utils/downloaders.py", line 164, in download_and_store
    if (self.folder / self.title / filename).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1407, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long:

**Setup Information**
 - OS: debian linux
 - Cyberdrop Downloader Version # 2.5.0

I've made a fix for this, that if the filename is over 100 characters I truncate the name.  It's worked to solve the problem but thought it might be something you might want to include for others that run into this.

The fix is in downloader.py in the utils directory.

after this if on line 162:
if "?v=" in url:
    filename = filename.split('v=')[0]

I added this:
maxFileNameLength=100
if len(filename) > maxFileNameLength :
    fileext=filename.split('.')[-1]
    filename = filename.replace(filename, filename[:maxFileNameLength]+'.'+fileext)

**Comment by Jules-WinnfieldX** [comment]
Awesome, annoying bug. Thanks for putting in the leg work though. I'll add a fix for that in the next release.
