### ISSUE TITLE
Cannot upgrade to v5

### ISSUE THREAD

**Issue by despecial** [Jules-WinnfieldX/CyberDropDownloader#714]
No matter if I use `pip3 install --upgrade cyberdrop-dl `or download the v5.1.zip file and run the code, it stays on version 4.

Terminal output...
```
pip3 install --upgrade cyberdrop-dl --no-cache-dir
Collecting cyberdrop-dl
  Downloading cyberdrop_dl-4.2.231-py3-none-any.whl.metadata (22 kB)
  ....
Downloading cyberdrop_dl-4.2.231-py3-none-any.whl (101 kB)
Installing collected packages: cyberdrop-dl
Successfully installed cyberdrop-dl-4.2.231
```

Python version is 3.9 (which cyberdrop-dl)
`/Library/Frameworks/Python.framework/Versions/3.9/bin/cyberdrop-dl`

Any idea why this happens?

**Comment by Jules-WinnfieldX** [comment]
V5 requires python 10 or python 11, you likely have below that.

https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start

**Comment by despecial** [comment]
Thanks, but it still doesnt work.

```
Starting Cyberdrop-DL
We are running version 4.2.231 of Cyberdrop Downloader
No valid links found.

Checking for incomplete downloads
Purging empty directories
Finished downloading. Enjoy :)

Your version of Cyberdrop Downloader is outdated.
You are running version 4.2.231.
Please update to version 5.0.101
You can find out how to do that here:
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Qu
estions#how-to-update

If you enjoy using this program, please consider buying the developer a coffee
:)
https://www.buymeacoffee.com/juleswinnft
```

Same console: 
```
which python3
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3
```

**Comment by Jules-WinnfieldX** [comment]
delete the venv folder if you have one, then try again.

**Comment by despecial** [comment]
Ah, found another thread here and checked "which cyber..."
Removed the location and the venv folder. Now it starts at version 5 but throws other errors when selecting download
(I used a new config)

```
Checking for partial downloads...
Checking for empty folders...

Download Stats:
Downloaded 0 files
Previously Downloaded 0 files
Skipped By Config 0 files
Failed 0 files

Scrape Failures:

Download Failures:
Unhandled exception; stopping loop: 'Task exception was never retrieved'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:
```

(removed the rest of the error message)

**Comment by Jules-WinnfieldX** [comment]
In applications open the python 3.11 folder, run the install certificates file, delete the venv, and try one more time.

**Comment by despecial** [comment]
Thanks, the errors are gone now! Appreciate your quick support.

But it doesnt scrape anymore. added several new bunker links.
There is no error but also no try to scrape anything. "URLs.txt" is in the same folder

**Comment by Jules-WinnfieldX** [comment]
It's likely pointing to a different urls.txt file, you can use the edit location in ui to see where it's pointing.

**Comment by despecial** [comment]
Very confusing. In version 4, the Start mac.command, URLs.txt and Downloads folder where in the same location and it worked out without any configuration.

When i edit the URLs.txt from within the terminal dialogue, it downloads all the files. But not in the Downloads folder on the same level as the startup command.

When I edit the paths to URLs.txt and Downloads to the same location, it doesnt find any urls, nor does it download anything.
