### ISSUE TITLE
[BUG] coomer.party scrape failed with `'dict' object has no attribute 'url'`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#741]
relevant part of `downloader.log`:

```
ERROR    : 2023-12-18 18:21:58,041 : utilities.py:93 : Scrape Failed: https://coomer.party/<removed> ('dict' object has no attribute 'url')
ERROR    : 2023-12-18 18:21:58,044 : utilities.py:93 : Traceback (most recent call last):
  File "C:\Users\<removed>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 61, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<removed>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\coomer_crawler.py", line 65, in profile
    await self.handle_post_content(post, scrape_item, user, user_str)
  File "C:\Users\<removed>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 58, in wrapper
    link = args[0].url
           ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'url'
```

remaining part of the URL in case you need it (NSFW, will remove later): `onlyfans/user/darcylovesyou`.

**Comment by Jules-WinnfieldX** [comment]
5.1.12 going up now should fix it.
