### ISSUE TITLE
[BUG] Error When Sorting Enable. (Docker)

### ISSUE THREAD

**Issue by marioaugustorama** [Jules-WinnfieldX/CyberDropDownloader#749]
Hi Guys, 

I'm trying to create a "docker" version of cyberdrop, but i got this error when Sorting Files are True.

Sorting Downloads: Please Wait
Traceback (most recent call last):
  File "/usr/local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 129, in main
    asyncio.run(director(manager))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 100, in director
    await sorter.sort()
  File "/usr/local/lib/python3.11/site-packages/cyberdrop_dl/utils/sorting.py", line 88, in sort
    await self.sort_video(file, folder.name)
  File "/usr/local/lib/python3.11/site-packages/cyberdrop_dl/utils/sorting.py", line 182, in sort_video
    await self.move_cd(file, new_file)
  File "/usr/local/lib/python3.11/site-packages/cyberdrop_dl/utils/sorting.py", line 48, in move_cd
    file.rename(dest)
  File "/usr/local/lib/python3.11/pathlib.py", line 1175, in rename
    os.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: 

Running on Linux With Docker.

I Use Latest Version running with python 3.11

**Comment by Jules-WinnfieldX** [comment]
You can't sort across drives, needs to be the same
