### ISSUE TITLE
[BUG] (SSL related?) errors upon exit/finish

### ISSUE THREAD

**Issue by minirockets** [Jules-WinnfieldX/CyberDropDownloader#766]
**Describe the bug**
Ever since the launch of V5, I see this same error upon finishing a run of the script.  I've read the FAQ and updated via pip3. Let me know if I'm missing something obvious 

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Run cyberdrop-dl, wait for the exit sequence, 
2. see SSL related error messages

```
    Checking for partial downloads...
    Checking for empty folders...

    Download Stats:
    Downloaded 2 files
    Previously Downloaded 1 files
    Skipped By Config 0 files
    Failed 0 files

    Scrape Failures:

    Download Failures:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/Redacted/Library/Python/3.11/bin/cyberdrop-dl", line 8, in <module>
        sys.exit(main())
                ^^^^^^
      File "/Users/Redacted/Library/Python/3.11/lib/python/site-packages/cyberdrop_dl/main.py", line 129, in main
        asyncio.run(director(manager))
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
        return runner.run(main)
              ^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
        return self._loop.run_until_complete(task)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
              ^^^^^^^^^^^^^^^
      File "/Users/Redacted/Library/Python/3.11/lib/python/site-packages/cyberdrop_dl/main.py", line 112, in director
        await check_latest_pypi()
      File "/Users/Redacted/Library/Python/3.11/lib/python/site-packages/cyberdrop_dl/utils/utilities.py", line 233, in check_latest_pypi
        contents = urllib.request.urlopen('https://pypi.org/pypi/cyberdrop-dl/json').read()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, Redactedeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
        response = self._open(req, data)
                  ^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
        result = func(*args)
                ^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
```

**Setup Information**
 - Python 3.11, macOS 14.2
 - Cyberdrop Downloader Version 5.1.32

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13810042/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Run the install certificates file in the python folder in your applications folder. Then delete the `venv` folder where you are running Cyberdrop-DL (if there is one) and try again.

**Comment by minirockets** [comment]
Thanks so much @Jules-WinnfieldX ; exits cleanly now. This was not a cyberdrop-dl issue, so I apologize for my ignorance as I use python infrequently.
