### ISSUE TITLE
[BUG] Bunkr unknown error on scrape

### ISSUE THREAD

**Issue by chatoooo** [Jules-WinnfieldX/CyberDropDownloader#803]
It seems like Bunkr wants to change something every week. Now, they changed the URL for the download button, so the crawler cannot find the filename.

To fix this for a video, the lines
https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/6ac12429f15b3430b2334f94440b45cf07a51117/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py#L102-L103
needs to be changed to
```python
link_container = soup.select("video[id=player]>source")[-1]
link = URL(link_container.get('src'))
```
then the download works again.

**Comment by Jules-WinnfieldX** [comment]
can you share a log with a link where the current build doesn't work?

**Comment by chatoooo** [comment]
```2024-02-01 22:06:00,622:utilities.py:81:Scrape Failed: https://bunkr.ws/v/AmdNqMvuN4PlH (Extension missing for file)
2024-02-01 22:06:00,623:utilities.py:81:Traceback (most recent call last):
  File "C:\Users\Honza\AppData\Roaming\Python\Python310\site-packages\cyberdrop_dl\scraper\crawlers\bunkrr_crawler.py", line 86, in video
    filename, ext = await get_filename_and_ext(link.name)
  File "C:\Users\Honza\AppData\Roaming\Python\Python310\site-packages\cyberdrop_dl\utils\utilities.py", line 130, in get_filename_and_ext
    raise NoExtensionFailure()
cyberdrop_dl.clients.errors.NoExtensionFailure: Extension missing for file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Honza\AppData\Roaming\Python\Python310\site-packages\cyberdrop_dl\utils\utilities.py", line 56, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Honza\AppData\Roaming\Python\Python310\site-packages\cyberdrop_dl\scraper\crawlers\bunkrr_crawler.py", line 88, in video
    filename, ext = await get_filename_and_ext(scrape_item.url.name)
  File "C:\Users\Honza\AppData\Roaming\Python\Python310\site-packages\cyberdrop_dl\utils\utilities.py", line 130, in get_filename_and_ext
    raise NoExtensionFailure()
cyberdrop_dl.clients.errors.NoExtensionFailure: Extension missing for file

2024-02-01 22:06:00,624:utilities.py:81:Scrape Finished: https://bunkr.ws/v/AmdNqMvuN4PlH```

**Comment by Jules-WinnfieldX** [comment]
Can I see the full log?

**Comment by chatoooo** [comment]
Sorry my bad, I found that I'm using not the latest version because I was running Python 3.10. The latest version works. It would be nice to show the need of Python upgrade in the app.

**Comment by Jules-WinnfieldX** [comment]
If you are running 5.0.124 it does say you need to in the update available message

**Comment by chatoooo** [comment]
Where exactly? I see it in the log only. I switched back to 3.10. New folder. Downloaded the latest start files. Started `Start Windows.bat`. I end up in 5.0.124. No message about need of upgrade python to get to 5.1.

**Comment by Jules-WinnfieldX** [comment]
it's a message after a run completes, as it always has been with CDL

**Comment by chatoooo** [comment]
It would be better to have it at the startup as something like a modal window 😄
