### ISSUE TITLE
[BUG] You are running version 4.2.231. Please update to version 5.1.68

### ISSUE THREAD

**Issue by justavideogame** [Jules-WinnfieldX/CyberDropDownloader#816]
I am getting this bug even though this is a new download, cant seem to fix it

Checking for incomplete downloads
Purging empty directories
Finished downloading. Enjoy :)

Your version of Cyberdrop Downloader is outdated.
You are running version 4.2.231.
Please update to version 5.1.68
You can find out how to do that here:
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

If you enjoy using this program, please consider buying the developer a coffee :)
https://www.buymeacoffee.com/juleswinnft

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A72D3BC820>
Traceback (most recent call last):
  File "C:\Users\steve\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\steve\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\steve\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Press any key to continue . . .

**Comment by Jules-WinnfieldX** [comment]
You need to update to python 3.11

**Comment by justavideogame** [comment]
still doesnt fix it
