### ISSUE TITLE
[FEATURE] improve saint2.su handling of "not found" case

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#835]
here's an example link: `https://saint2.su/embed/0pubGMgiuC3`

apparently they treat it as 404 or something similar. Although instead of returning a true HTTP error they're trying to be funny with a gif.

today it results in an unhandled exception.

Scrape_Error_URLs.csv:
```
https://saint2.su/embed/0pubGMgiuC3, See Log for Details
```

downloader.log
```
INFO     : 2024-03-03 16:14:05,710 : utilities.py:98 : Scrape Starting: https://saint2.su/embed/0pubGMgiuC3
ERROR    : 2024-03-03 16:14:08,682 : utilities.py:98 : Scrape Failed: https://saint2.su/embed/0pubGMgiuC3 ('NoneType' object has no attribute 'get')
ERROR    : 2024-03-03 16:14:08,705 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\saint_crawler.py", line 42, in video
    link = URL(soup.select_one('video[id=main-video] source').get('src'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

INFO     : 2024-03-03 16:14:08,707 : utilities.py:98 : Scrape Finished: https://saint2.su/embed/0pubGMgiuC3
```

Ideally I would prefer not to see "See Log for Details" because it's counter-productive and makes me dig through downloader.log. It looks like a pretty standard case for saint2.su, so there should be a better way to handle this.

**Comment by Jules-WinnfieldX** [comment]
Will be handled in next update later today
