### ISSUE TITLE
[FEATURE] Improve handling of password-protected GoFile links

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#867]
here's an example link: `https://gofile.io/d/ucglEf`.

today it causes a generic failure. From Scrape_Error_URLs.csv:
```
https://gofile.io/d/ucglEf, See Log for Details
```

downloader.log:
```
INFO     : 2024-04-03 09:08:04,026 : utilities.py:98 : Scrape Starting: https://gofile.io/d/ucglEf
ERROR    : 2024-04-03 09:08:06,912 : utilities.py:98 : Scrape Failed: https://gofile.io/d/ucglEf ('name')
ERROR    : 2024-04-03 09:08:06,912 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\gofile_crawler.py", line 66, in album
    title = await self.create_title(JSON_Resp["name"], content_id, None)
                                    ~~~~~~~~~^^^^^^^^
KeyError: 'name'
INFO     : 2024-04-03 09:08:06,912 : utilities.py:98 : Scrape Finished: https://gofile.io/d/ucglEf
```

I would propose that CDL handles this scenario more grasefully and put something like this into Scrape_Error_URLs.csv
```
https://gofile.io/d/ucglEf, password protected
```

**Comment by baccccccc** [comment]
also if CDL does not support password-protected links by design, they probably should go to `Unsupported_URLs` instead of `Scrape_Error_URLs`.

**Comment by Jules-WinnfieldX** [comment]
You guessed it, 5.2.22
