### ISSUE TITLE
[BUG] `'NoneType' object has no attribute 'get'` on imgbox

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#887]
Here's the URL which works in the browser
```
https://imgbox.com/gallery/edit/tFuobjpvcq/vy3Af1AlSJYsHnr6, See Log for Details
```

CDL is unhappy for some reason
```
INFO     : 2024-04-19 21:26:30,615 : utilities.py:103 : Scrape Starting: https://imgbox.com/gallery/edit/tFuobjpvcq/vy3Af1AlSJYsHnr6
ERROR    : 2024-04-19 21:26:31,707 : utilities.py:103 : Scrape Failed: 	 ('NoneType' object has no attribute 'get')
ERROR    : 2024-04-19 21:26:31,727 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\imgbox_crawler.py", line 66, in image
    image = URL(soup.select_one("img[id=img]").get('src'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

INFO     : 2024-04-19 21:26:31,728 : utilities.py:103 : Scrape Finished: https://imgbox.com/gallery/edit/tFuobjpvcq/vy3Af1AlSJYsHnr6
```

**Comment by Jules-WinnfieldX** [comment]
It's unhappy because that's the edit link for the gallery. Allowing you to edit or delete said gallery. 

https://imgbox.com/g/tFuobjpvcq

This is what the actual album link is.

5.2.42 will add the conversion internally. As much as I hate doing so.
