### ISSUE TITLE
[FEATURE] Improve handling of password-protected links on cyberfile

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#888]
same deal as #867.

here are some examples.
```
https://cyberfile.me/ey2f, See Log for Details
https://cyberfile.me/ey2e, See Log for Details
https://cyberfile.me/alT8, See Log for Details
```

current behavior:
```
INFO     : 2024-04-19 21:24:18,369 : utilities.py:103 : Scrape Starting: https://cyberfile.me/alT8
ERROR    : 2024-04-19 21:24:25,355 : utilities.py:103 : Scrape Failed: https://cyberfile.me/alT8 ('NoneType' object has no attribute 'get')
ERROR    : 2024-04-19 21:24:25,371 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\cyberfile_crawler.py", line 154, in handle_content_id
    html_download_text = file_button.get("onclick")
                         ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

INFO     : 2024-04-19 21:24:25,375 : utilities.py:103 : Scrape Finished: https://cyberfile.me/alT8
```

**Comment by Jules-WinnfieldX** [comment]
5.2.41 should add the proper failure
