### ISSUE TITLE
[BUG] `KeyError: 'name'` when scraping gofile

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#890]
as it happened a few times before, here's a perfectly good gofile URL. It works in the browser and allows downloading.
```
https://cold2.gofile.io/download/1a054f0c-bd84-4c8d-8b47-6551f0d7243b/Jerkmate%20-%20Amouranth%202023-12-26%2019_56%20Holiday%20edition.mp4, See Log for Details
```

but CDL dislikes it.
```
INFO     : 2024-04-23 14:41:05,768 : utilities.py:103 : Scrape Starting: https://cold2.gofile.io/download/1a054f0c-bd84-4c8d-8b47-6551f0d7243b/Jerkmate%20-%20Amouranth%202023-12-26%2019_56%20Holiday%20edition.mp4
ERROR    : 2024-04-23 14:41:07,741 : utilities.py:103 : Scrape Failed: https://cold2.gofile.io/download/1a054f0c-bd84-4c8d-8b47-6551f0d7243b/Jerkmate%20-%20Amouranth%202023-12-26%2019_56%20Holiday%20edition.mp4 ('name')
ERROR    : 2024-04-23 14:41:07,762 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\gofile_crawler.py", line 68, in album
    title = await self.create_title(JSON_Resp["name"], content_id, None)
                                    ~~~~~~~~~^^^^^^^^
KeyError: 'name'

INFO     : 2024-04-23 14:41:07,771 : utilities.py:103 : Scrape Finished: https://cold2.gofile.io/download/1a054f0c-bd84-4c8d-8b47-6551f0d7243b/Jerkmate%20-%20Amouranth%202023-12-26%2019_56%20Holiday%20edition.mp4
```

**Comment by Jules-WinnfieldX** [comment]
CDL doesn't technically support direct links for GoFile. Initial loading of that page just sends you to the /d/ file page, which CDL can handle. However there is no way to transform the URL into the /D/ page, which is why it isn't supported.
