### ISSUE TITLE
[BUG] scraping a Zip on bunkr fails with `IndexError: list index out of range`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#892]
I think it's a comeback of #836. Once that feature request was closed, it worked for me indeed. But now it seems broken again. Not sure if it's one particular nasty zip or a class issue.

```
https://get.bunkrr.su/file/15934404, See Log for Details
```

```
ERROR    : 2024-05-04 16:22:41,011 : utilities.py:103 : Scrape Failed: https://get.bunkrr.su/file/15934404 (list index out of range)
ERROR    : 2024-05-04 16:22:41,049 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\bunkrr_crawler.py", line 142, in other
    filename, ext = await get_filename_and_ext(link.name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 162, in get_filename_and_ext
    raise NoExtensionFailure()
cyberdrop_dl.clients.errors.NoExtensionFailure: Extension missing for file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\bunkrr_crawler.py", line 161, in reinforced_link
    link_container = soup.select('a[download*=""]')[-1]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

INFO     : 2024-05-04 16:22:41,051 : utilities.py:103 : Scrape Finished: https://bunkr.sk/d/Nikki-Benz-Onlyfans-Pics-gxRwxBOD.zip
```

**Comment by Jules-WinnfieldX** [comment]
5.2.53 will solve this.

**Comment by baccccccc** [comment]
Thanks! It indeed worked.

P.S. one more housekeeping question. In a cases like this (or #889) when a new issue is a follow-up to an older issue, do you prefer us to open a separate issue or re-open the old one?

**Comment by Jules-WinnfieldX** [comment]
I’m alright with either as long as it’s documented
