### ISSUE TITLE
[BUG] nonexistent files on gofile are reported as “Unknown” instead of a 404 (recent chance)

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#909]
I believe it was working correctly until around a week ago. I.e. When scraping a particular forum thread, I received something like this.
```
Scrape Failures:
Scrape Failures (404 HTTP Status): 8
```

but now scraping the same thread returns this.
```
Scrape Failures:
Scrape Failures (Unknown): 8
```

Scrape_Error_URLs.csv
```
https://gofile.io/d/CtCrSb, See Log for Details
https://gofile.io/d/7z2qMa, See Log for Details
https://gofile.io/d/3625Vp, See Log for Details
https://gofile.io/d/SAuV7j, See Log for Details
https://gofile.io/d/fVn8vR, See Log for Details
https://gofile.io/d/G6CpsP, See Log for Details
https://gofile.io/d/Hfjymx, See Log for Details
https://gofile.io/d/LpgYv3, See Log for Details
```

excerpt from downloader.log
```
INFO     : 2024-06-04 08:29:29,531 : utilities.py:103 : Scrape Starting: https://gofile.io/d/CtCrSb
ERROR    : 2024-06-04 08:29:31,813 : utilities.py:103 : Scrape Failed: https://gofile.io/d/CtCrSb ('name')
ERROR    : 2024-06-04 08:29:31,845 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\gofile_crawler.py", line 68, in album
    title = await self.create_title(JSON_Resp["name"], content_id, None)
                                    ~~~~~~~~~^^^^^^^^
KeyError: 'name'

INFO     : 2024-06-04 08:29:31,848 : utilities.py:103 : Scrape Finished: https://gofile.io/d/CtCrSb
```

**Comment by Jules-WinnfieldX** [comment]
Fixed in 5.3.26
