### ISSUE TITLE
[BUG] no such option: --update error

### ISSUE THREAD

**Issue by dynbabaul** [Jules-WinnfieldX/CyberDropDownloader#96]
Using Cyberdrop_DL.V2.zip and running on linux I get this error:

./Start\ Linux.sh

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --update
Traceback (most recent call last):
  File "/home/mux/.local/bin/cyberdrop-dl", line 6, in <module>
    from cyberdrop_dl.main import main
  File "/home/mux/.local/lib/python3.7/site-packages/cyberdrop_dl/main.py", line 14, in <module>
    from .utils.downloaders import get_downloaders
  File "/home/mux/.local/lib/python3.7/site-packages/cyberdrop_dl/utils/downloaders.py", line 249, in <module>
    def get_downloaders(urls: dict[str, dict[str, list[str]]], cookies: Iterable[str], folder: Path, attempts: int, threads: int) -> list[Downloader]:
TypeError: 'type' object is not subscriptable
./Start Linux.sh: 5: ./Start Linux.sh: pause: not found

**Comment by Jules-WinnfieldX** [comment]
Yikes haha, I'll upgrade that start script in a few hours. I'll reply again when I do.
